import type { Locale } from '@/lib/i18n'

// Vertalingen voor de landingspagina. Prijs-tokens: {sym} = muntsymbool, {p0} = starterprijs.
export interface LandingCopy {
  nav: { browseStyles: string; whyUs: string; plans: string; howItWorks: string; help: string; login: string; getStarted: string; dashboard: string }
  hero: {
    badge: string; title1: string; title2: string; subtitle: string
    ctaPrimary: string; ctaSecondary: string; curious: string; seeWomen: string; seeMen: string
    trust: [string, string, string]; sliderBefore: string; sliderAfter: string
  }
  valueBar: { delivery: string; styles: string; startingPrice: string; guarantee: string }
  how: { heading: string; sub: string; videoTitle: string; videoSoon: string; steps: { title: string; desc: string }[] }
  results: { heading: string; sub: string; before: string; after: string; cta: string; quotes: string[] }
  features: { heading: string; sub: string; items: { title: string; desc: string }[] }
  pricing: {
    heading: string; sub: string; note: string; oneTime: string; bestValue: string; getStarted: string; footnote: string
    tiers: { name: string; line: string; features: string[] }[]
    guarantee: { title: string; body: string; items: [string, string, string] }
  }
  faq: { heading: string; items: { q: string; a: string }[] }
  finalCta: { heading: string; sub: string; cta: string; badge: string }
  footer: {
    product: string; company: string; useCases: string; legal: string; about: string; contact: string; rights: string
    productItems: [string, string, string, string]; useCaseItems: [string, string, string, string]; legalItems: [string, string, string, string]
  }
}

const en: LandingCopy = {
  nav: { browseStyles: 'Browse Styles', whyUs: 'Why Us', plans: 'Plans', howItWorks: 'How It Works', help: 'Help', login: 'Login', getStarted: 'Get Started →', dashboard: 'Dashboard →' },
  hero: {
    badge: 'Powered by FLUX AI — the most realistic model available',
    title1: 'Turn Your Selfies Into', title2: 'Professional Headshots',
    subtitle: 'Upload 8–15 photos. Choose your style. Get studio-quality headshots in under 30 minutes — without a photographer, studio, or expensive session.',
    ctaPrimary: 'Get Your Headshots Now →', ctaSecondary: 'View Pricing',
    curious: '✨ Curious? Take a look around — no signup needed', seeWomen: "See women's styles →", seeMen: "See men's styles →",
    trust: ['Ready in 30 minutes', 'Profile-Worthy Guarantee', '100% private & secure'], sliderBefore: 'Your Selfie', sliderAfter: 'AI Headshot',
  },
  valueBar: { delivery: 'Average delivery time', styles: 'Unique styles available', startingPrice: 'Starting price', guarantee: 'Profile-Worthy Guarantee' },
  how: {
    heading: 'How It Works', sub: 'Three simple steps to your perfect headshot', videoTitle: 'See how it works in 90 seconds', videoSoon: 'Video coming soon',
    steps: [
      { title: 'Upload Your Photos', desc: 'Upload 8–15 selfies from different angles and lighting conditions. No professional equipment needed.' },
      { title: 'Choose Your Styles', desc: 'Pick from 45+ hand-curated styles — corporate, casual, creative, outdoor, restaurant, and more. Each style generates 4 unique variations.' },
      { title: 'Receive Your Headshots', desc: 'Your AI-generated headshots are ready in under 30 minutes. Download and use them anywhere.' },
    ],
  },
  results: {
    heading: 'Real People. Real Results.', sub: 'These headshots were generated by Nova Imago. No photographer. No studio.', before: 'Before', after: 'AI Headshot', cta: 'Get Your Headshots Now →',
    quotes: [
      "I couldn't believe how realistic it looks. Using it on LinkedIn right away!",
      'Incredible result — looks completely natural and professional.',
      'I was amazed by the quality. Perfect for my professional profile!',
      'Absolutely stunning results. Looks just like me but even better!',
      'Amazing quality — I use it on my LinkedIn profile now!',
      'The results exceeded my expectations. So natural and professional!',
    ],
  },
  features: {
    heading: 'Why Professionals Choose Us', sub: 'Studio-quality headshots without the studio price tag',
    items: [
      { title: 'Results in 30 Minutes', desc: 'Upload your selfies and receive professional headshots in under 30 minutes. No waiting days for a photographer.' },
      { title: '45+ Curated Styles', desc: 'Corporate executive, smart casual, creative, outdoor, restaurant, and date night — hand-tuned for consistent quality. Each style produces 4 unique variations.' },
      { title: 'Powered by FLUX AI', desc: 'We use the most advanced AI model available, specifically fine-tuned on your photos for maximum realism.' },
      { title: 'Your Photos Stay Private', desc: 'Your photos are encrypted, never shared or sold, and automatically deleted after your order is complete.' },
      { title: 'Save {sym}200–{sym}500', desc: 'A professional photographer charges {sym}300–{sym}700 for one session. Get unlimited variations starting at just {sym}{p0}.' },
      { title: 'Profile-Worthy Guarantee', desc: 'We guarantee at least 1 profile-worthy headshot in every order — or your money back within 7 days. No questions asked.' },
    ],
  },
  pricing: {
    heading: 'Simple, Honest Pricing', sub: 'One-time payment. No subscriptions. No hidden fees.', note: 'Every style generates 4 unique variations.', oneTime: 'One-time payment', bestValue: 'Best Value', getStarted: 'Get Started →', footnote: 'One-time payment • No subscription ever',
    tiers: [
      { name: 'Starter', line: '40 headshots • 10 styles', features: ['1 AI model training', '40 HD headshots', 'Choose 10 styles × 4 variations', '45+ styles to choose from', 'HD quality', 'Ready in 30 minutes'] },
      { name: 'Pro', line: '80 headshots • 20 styles', features: ['1 AI model training', '80 HD headshots', 'Choose 20 styles × 4 variations', '45+ styles to choose from', 'HD quality', 'Ready in 30 minutes'] },
      { name: 'Premium', line: '120 headshots • 30 styles', features: ['2 AI model trainings', '120 HD headshots', 'Choose 30 styles × 4 variations', '45+ styles to choose from', 'HD quality', 'Ready in 30 minutes'] },
    ],
    guarantee: { title: 'Profile-Worthy Guarantee', body: "Not every photo will be perfect — that's the nature of AI. But we guarantee you'll get at least 1 profile-worthy headshot in every order. If not, we refund you in full within 7 days. No forms, no hassle.", items: ['Full refund within 7 days', 'No questions asked', 'No forms or hassle'] },
  },
  faq: {
    heading: 'Common Questions',
    items: [
      { q: 'How realistic are the AI-generated headshots?', a: 'We use FLUX LoRA — the most advanced AI portrait model available. The AI is trained specifically on your photos, which means the results look like you, not a generic AI person.' },
      { q: 'What kind of photos should I upload?', a: 'Upload 8–15 clear solo photos with good lighting from different angles. Avoid group photos, sunglasses, heavy filters, or blurry images. The more variety, the better the result.' },
      { q: 'How long does it take?', a: 'Training your personal AI model takes about 20–25 minutes. After that, each style generates 4 variations in about 30 seconds.' },
      { q: 'Are my photos safe?', a: 'Yes. Your photos are stored securely, never shared with third parties, and deleted automatically after your order is complete.' },
      { q: 'What if I am not happy with the results?', a: 'We guarantee at least 1 profile-worthy headshot in every order. If not, we refund you in full within 7 days. No forms, no hassle — just contact us.' },
      { q: 'Can I use these headshots commercially?', a: 'Yes. You own the rights to every headshot we generate for you. Use them on LinkedIn, your website, business cards, or anywhere else.' },
    ],
  },
  finalCta: { heading: 'Your Best Photo Is One Upload Away', sub: 'No photographer. No studio. No awkward posing. Just upload your selfies and let the AI do the work.', cta: 'Get Started — From {sym}{p0} →', badge: 'Profile-Worthy Guarantee • Zero Risk' },
  footer: {
    product: 'Product', company: 'Company', useCases: 'Use Cases', legal: 'Legal', about: 'About', contact: 'Contact', rights: '© 2026 Nova Imago • All rights reserved',
    productItems: ['Features', 'Pricing', 'How It Works', 'FAQ'], useCaseItems: ['LinkedIn Headshots', 'Resume Photos', 'Dating Profile', 'Business Portraits'], legalItems: ['Terms of Service', 'Privacy Policy', 'Refund Policy', 'Cookie Policy'],
  },
}

const nl: LandingCopy = {
  nav: { browseStyles: 'Bekijk stijlen', whyUs: 'Waarom wij', plans: 'Prijzen', howItWorks: 'Hoe het werkt', help: 'Help', login: 'Inloggen', getStarted: 'Aan de slag →', dashboard: 'Dashboard →' },
  hero: {
    badge: 'Aangedreven door FLUX AI — het meest realistische model',
    title1: 'Zet je selfies om in', title2: 'Professionele headshots',
    subtitle: 'Upload 8–15 foto’s. Kies je stijl. Krijg headshots van studiokwaliteit in minder dan 30 minuten — zonder fotograaf, studio of dure sessie.',
    ctaPrimary: 'Nu je headshots maken →', ctaSecondary: 'Bekijk prijzen',
    curious: '✨ Benieuwd? Kijk gerust rond — geen account nodig', seeWomen: 'Vrouwenstijlen bekijken →', seeMen: 'Mannenstijlen bekijken →',
    trust: ['Klaar in 30 minuten', 'Profielwaardig-garantie', '100% privé & veilig'], sliderBefore: 'Jouw selfie', sliderAfter: 'AI-headshot',
  },
  valueBar: { delivery: 'Gemiddelde levertijd', styles: 'Unieke stijlen beschikbaar', startingPrice: 'Vanafprijs', guarantee: 'Profielwaardig-garantie' },
  how: {
    heading: 'Hoe het werkt', sub: 'Drie eenvoudige stappen naar jouw perfecte headshot', videoTitle: 'Zie in 90 seconden hoe het werkt', videoSoon: 'Video komt binnenkort',
    steps: [
      { title: 'Upload je foto’s', desc: 'Upload 8–15 selfies vanuit verschillende hoeken en lichtomstandigheden. Geen professionele apparatuur nodig.' },
      { title: 'Kies je stijlen', desc: 'Kies uit 45+ zorgvuldig samengestelde stijlen — zakelijk, casual, creatief, outdoor, restaurant en meer. Elke stijl levert 4 unieke variaties.' },
      { title: 'Ontvang je headshots', desc: 'Je AI-headshots zijn klaar in minder dan 30 minuten. Download ze en gebruik ze overal.' },
    ],
  },
  results: {
    heading: 'Echte mensen. Echte resultaten.', sub: 'Deze headshots zijn gemaakt met Nova Imago. Geen fotograaf. Geen studio.', before: 'Voor', after: 'AI-headshot', cta: 'Nu je headshots maken →',
    quotes: [
      'Ik kon niet geloven hoe realistisch het eruitziet. Meteen op LinkedIn gezet!',
      'Ongelooflijk resultaat — ziet er volledig natuurlijk en professioneel uit.',
      'Ik was verbaasd over de kwaliteit. Perfect voor mijn professionele profiel!',
      'Absoluut prachtige resultaten. Precies zoals ik, maar nog beter!',
      'Geweldige kwaliteit — ik gebruik het nu op mijn LinkedIn-profiel!',
      'De resultaten overtroffen mijn verwachtingen. Zo natuurlijk en professioneel!',
    ],
  },
  features: {
    heading: 'Waarom professionals voor ons kiezen', sub: 'Studiokwaliteit zonder het prijskaartje van een studio',
    items: [
      { title: 'Resultaten in 30 minuten', desc: 'Upload je selfies en ontvang professionele headshots in minder dan 30 minuten. Geen dagen wachten op een fotograaf.' },
      { title: '45+ samengestelde stijlen', desc: 'Zakelijk executive, smart casual, creatief, outdoor, restaurant en date night — verfijnd voor consistente kwaliteit. Elke stijl levert 4 unieke variaties.' },
      { title: 'Aangedreven door FLUX AI', desc: 'We gebruiken het meest geavanceerde AI-model, specifiek afgestemd op jouw foto’s voor maximaal realisme.' },
      { title: 'Je foto’s blijven privé', desc: 'Je foto’s worden versleuteld, nooit gedeeld of verkocht, en automatisch verwijderd nadat je bestelling klaar is.' },
      { title: 'Bespaar {sym}200–{sym}500', desc: 'Een professionele fotograaf rekent {sym}300–{sym}700 voor één sessie. Krijg onbeperkte variaties vanaf slechts {sym}{p0}.' },
      { title: 'Profielwaardig-garantie', desc: 'We garanderen minstens 1 profielwaardige headshot in elke bestelling — of je geld terug binnen 7 dagen. Geen gedoe.' },
    ],
  },
  pricing: {
    heading: 'Simpele, eerlijke prijzen', sub: 'Eenmalige betaling. Geen abonnement. Geen verborgen kosten.', note: 'Elke stijl levert 4 unieke variaties.', oneTime: 'Eenmalige betaling', bestValue: 'Beste keuze', getStarted: 'Aan de slag →', footnote: 'Eenmalige betaling • Nooit een abonnement',
    tiers: [
      { name: 'Starter', line: '40 headshots • 10 stijlen', features: ['1 AI-model training', '40 HD-headshots', 'Kies 10 stijlen × 4 variaties', '45+ stijlen om uit te kiezen', 'HD-kwaliteit', 'Klaar in 30 minuten'] },
      { name: 'Pro', line: '80 headshots • 20 stijlen', features: ['1 AI-model training', '80 HD-headshots', 'Kies 20 stijlen × 4 variaties', '45+ stijlen om uit te kiezen', 'HD-kwaliteit', 'Klaar in 30 minuten'] },
      { name: 'Premium', line: '120 headshots • 30 stijlen', features: ['2 AI-model trainingen', '120 HD-headshots', 'Kies 30 stijlen × 4 variaties', '45+ stijlen om uit te kiezen', 'HD-kwaliteit', 'Klaar in 30 minuten'] },
    ],
    guarantee: { title: 'Profielwaardig-garantie', body: 'Niet elke foto zal perfect zijn — dat is de aard van AI. Maar we garanderen minstens 1 profielwaardige headshot in elke bestelling. Zo niet, dan betalen we je volledig terug binnen 7 dagen. Geen formulieren, geen gedoe.', items: ['Volledige terugbetaling binnen 7 dagen', 'Geen vragen gesteld', 'Geen formulieren of gedoe'] },
  },
  faq: {
    heading: 'Veelgestelde vragen',
    items: [
      { q: 'Hoe realistisch zijn de AI-headshots?', a: 'We gebruiken FLUX LoRA — het meest geavanceerde AI-portretmodel. De AI wordt specifiek op jouw foto’s getraind, waardoor de resultaten op jou lijken, niet op een generiek AI-persoon.' },
      { q: 'Welke foto’s moet ik uploaden?', a: 'Upload 8–15 duidelijke solofoto’s met goed licht vanuit verschillende hoeken. Vermijd groepsfoto’s, zonnebrillen, zware filters of wazige beelden. Hoe meer variatie, hoe beter het resultaat.' },
      { q: 'Hoe lang duurt het?', a: 'Het trainen van je persoonlijke AI-model duurt ongeveer 20–25 minuten. Daarna levert elke stijl 4 variaties in ongeveer 30 seconden.' },
      { q: 'Zijn mijn foto’s veilig?', a: 'Ja. Je foto’s worden veilig bewaard, nooit met derden gedeeld en automatisch verwijderd nadat je bestelling klaar is.' },
      { q: 'Wat als ik niet tevreden ben?', a: 'We garanderen minstens 1 profielwaardige headshot in elke bestelling. Zo niet, dan betalen we je volledig terug binnen 7 dagen. Geen gedoe — neem gewoon contact op.' },
      { q: 'Mag ik deze headshots commercieel gebruiken?', a: 'Ja. Jij bezit de rechten op elke headshot die we voor je maken. Gebruik ze op LinkedIn, je website, visitekaartjes of waar je maar wil.' },
    ],
  },
  finalCta: { heading: 'Je beste foto is één upload verwijderd', sub: 'Geen fotograaf. Geen studio. Geen ongemakkelijk poseren. Upload gewoon je selfies en laat de AI het werk doen.', cta: 'Aan de slag — vanaf {sym}{p0} →', badge: 'Profielwaardig-garantie • Zonder risico' },
  footer: {
    product: 'Product', company: 'Bedrijf', useCases: 'Toepassingen', legal: 'Juridisch', about: 'Over ons', contact: 'Contact', rights: '© 2026 Nova Imago • Alle rechten voorbehouden',
    productItems: ['Kenmerken', 'Prijzen', 'Hoe het werkt', 'FAQ'], useCaseItems: ['LinkedIn-headshots', 'CV-foto’s', 'Datingprofiel', 'Zakelijke portretten'], legalItems: ['Gebruiksvoorwaarden', 'Privacybeleid', 'Terugbetalingsbeleid', 'Cookiebeleid'],
  },
}

const fr: LandingCopy = {
  nav: { browseStyles: 'Voir les styles', whyUs: 'Pourquoi nous', plans: 'Tarifs', howItWorks: 'Comment ça marche', help: 'Aide', login: 'Connexion', getStarted: 'Commencer →', dashboard: 'Tableau de bord →' },
  hero: {
    badge: 'Propulsé par FLUX AI — le modèle le plus réaliste disponible',
    title1: 'Transformez vos selfies en', title2: 'Portraits professionnels',
    subtitle: 'Importez 8 à 15 photos. Choisissez votre style. Obtenez des portraits de qualité studio en moins de 30 minutes — sans photographe, studio ni séance coûteuse.',
    ctaPrimary: 'Obtenir mes portraits →', ctaSecondary: 'Voir les tarifs',
    curious: '✨ Curieux ? Jetez un œil — aucune inscription requise', seeWomen: 'Voir les styles femme →', seeMen: 'Voir les styles homme →',
    trust: ['Prêt en 30 minutes', 'Garantie photo de profil', '100% privé et sécurisé'], sliderBefore: 'Votre selfie', sliderAfter: 'Portrait IA',
  },
  valueBar: { delivery: 'Délai de livraison moyen', styles: 'Styles uniques disponibles', startingPrice: 'Prix de départ', guarantee: 'Garantie photo de profil' },
  how: {
    heading: 'Comment ça marche', sub: 'Trois étapes simples vers votre portrait parfait', videoTitle: 'Découvrez comment ça marche en 90 secondes', videoSoon: 'Vidéo bientôt disponible',
    steps: [
      { title: 'Importez vos photos', desc: 'Importez 8 à 15 selfies sous différents angles et éclairages. Aucun équipement professionnel requis.' },
      { title: 'Choisissez vos styles', desc: 'Choisissez parmi plus de 45 styles soignés — corporate, décontracté, créatif, extérieur, restaurant et plus. Chaque style génère 4 variations uniques.' },
      { title: 'Recevez vos portraits', desc: 'Vos portraits générés par IA sont prêts en moins de 30 minutes. Téléchargez-les et utilisez-les partout.' },
    ],
  },
  results: {
    heading: 'De vraies personnes. De vrais résultats.', sub: 'Ces portraits ont été générés par Nova Imago. Sans photographe. Sans studio.', before: 'Avant', after: 'Portrait IA', cta: 'Obtenir mes portraits →',
    quotes: [
      'Je n’en revenais pas du réalisme. Je l’utilise sur LinkedIn tout de suite !',
      'Résultat incroyable — totalement naturel et professionnel.',
      'La qualité m’a bluffé. Parfait pour mon profil professionnel !',
      'Des résultats absolument superbes. C’est bien moi, en encore mieux !',
      'Qualité incroyable — je l’utilise maintenant sur mon profil LinkedIn !',
      'Les résultats ont dépassé mes attentes. Si naturel et professionnel !',
    ],
  },
  features: {
    heading: 'Pourquoi les professionnels nous choisissent', sub: 'Une qualité studio sans le prix du studio',
    items: [
      { title: 'Résultats en 30 minutes', desc: 'Importez vos selfies et recevez des portraits professionnels en moins de 30 minutes. Plus besoin d’attendre un photographe pendant des jours.' },
      { title: 'Plus de 45 styles soignés', desc: 'Cadre executive, smart casual, créatif, extérieur, restaurant et date night — affinés pour une qualité constante. Chaque style produit 4 variations uniques.' },
      { title: 'Propulsé par FLUX AI', desc: 'Nous utilisons le modèle d’IA le plus avancé, spécifiquement affiné sur vos photos pour un réalisme maximal.' },
      { title: 'Vos photos restent privées', desc: 'Vos photos sont chiffrées, jamais partagées ni vendues, et supprimées automatiquement une fois votre commande terminée.' },
      { title: 'Économisez {sym}200–{sym}500', desc: 'Un photographe professionnel facture {sym}300–{sym}700 pour une séance. Obtenez des variations illimitées à partir de seulement {sym}{p0}.' },
      { title: 'Garantie photo de profil', desc: 'Nous garantissons au moins 1 portrait digne d’un profil dans chaque commande — ou remboursé sous 7 jours. Sans condition.' },
    ],
  },
  pricing: {
    heading: 'Des tarifs simples et honnêtes', sub: 'Paiement unique. Sans abonnement. Sans frais cachés.', note: 'Chaque style génère 4 variations uniques.', oneTime: 'Paiement unique', bestValue: 'Meilleur choix', getStarted: 'Commencer →', footnote: 'Paiement unique • Jamais d’abonnement',
    tiers: [
      { name: 'Starter', line: '40 portraits • 10 styles', features: ['1 entraînement de modèle IA', '40 portraits HD', 'Choisissez 10 styles × 4 variations', 'Plus de 45 styles au choix', 'Qualité HD', 'Prêt en 30 minutes'] },
      { name: 'Pro', line: '80 portraits • 20 styles', features: ['1 entraînement de modèle IA', '80 portraits HD', 'Choisissez 20 styles × 4 variations', 'Plus de 45 styles au choix', 'Qualité HD', 'Prêt en 30 minutes'] },
      { name: 'Premium', line: '120 portraits • 30 styles', features: ['2 entraînements de modèle IA', '120 portraits HD', 'Choisissez 30 styles × 4 variations', 'Plus de 45 styles au choix', 'Qualité HD', 'Prêt en 30 minutes'] },
    ],
    guarantee: { title: 'Garantie photo de profil', body: 'Toutes les photos ne seront pas parfaites — c’est la nature de l’IA. Mais nous garantissons au moins 1 portrait digne d’un profil dans chaque commande. Sinon, nous vous remboursons intégralement sous 7 jours. Sans formulaire, sans tracas.', items: ['Remboursement intégral sous 7 jours', 'Sans condition', 'Sans formulaire ni tracas'] },
  },
  faq: {
    heading: 'Questions fréquentes',
    items: [
      { q: 'Les portraits IA sont-ils réalistes ?', a: 'Nous utilisons FLUX LoRA — le modèle de portrait IA le plus avancé. L’IA est entraînée spécifiquement sur vos photos, ce qui fait que les résultats vous ressemblent, et non à une personne IA générique.' },
      { q: 'Quelles photos dois-je importer ?', a: 'Importez 8 à 15 photos solo nettes, bien éclairées, sous différents angles. Évitez les photos de groupe, lunettes de soleil, filtres lourds ou images floues. Plus il y a de variété, meilleur est le résultat.' },
      { q: 'Combien de temps cela prend-il ?', a: 'L’entraînement de votre modèle IA personnel prend environ 20 à 25 minutes. Ensuite, chaque style génère 4 variations en environ 30 secondes.' },
      { q: 'Mes photos sont-elles en sécurité ?', a: 'Oui. Vos photos sont stockées en sécurité, jamais partagées avec des tiers, et supprimées automatiquement une fois votre commande terminée.' },
      { q: 'Et si je ne suis pas satisfait ?', a: 'Nous garantissons au moins 1 portrait digne d’un profil dans chaque commande. Sinon, remboursement intégral sous 7 jours. Sans tracas — contactez-nous simplement.' },
      { q: 'Puis-je utiliser ces portraits commercialement ?', a: 'Oui. Vous détenez les droits sur chaque portrait que nous générons pour vous. Utilisez-les sur LinkedIn, votre site, vos cartes de visite ou ailleurs.' },
    ],
  },
  finalCta: { heading: 'Votre meilleure photo n’est qu’à un import', sub: 'Sans photographe. Sans studio. Sans poses gênantes. Importez vos selfies et laissez l’IA faire le travail.', cta: 'Commencer — à partir de {sym}{p0} →', badge: 'Garantie photo de profil • Zéro risque' },
  footer: {
    product: 'Produit', company: 'Entreprise', useCases: 'Cas d’usage', legal: 'Mentions légales', about: 'À propos', contact: 'Contact', rights: '© 2026 Nova Imago • Tous droits réservés',
    productItems: ['Fonctionnalités', 'Tarifs', 'Comment ça marche', 'FAQ'], useCaseItems: ['Portraits LinkedIn', 'Photos de CV', 'Profil de rencontre', 'Portraits d’entreprise'], legalItems: ['Conditions d’utilisation', 'Politique de confidentialité', 'Politique de remboursement', 'Politique de cookies'],
  },
}

const de: LandingCopy = {
  nav: { browseStyles: 'Stile ansehen', whyUs: 'Warum wir', plans: 'Preise', howItWorks: 'So funktioniert’s', help: 'Hilfe', login: 'Anmelden', getStarted: 'Loslegen →', dashboard: 'Dashboard →' },
  hero: {
    badge: 'Angetrieben von FLUX AI — dem realistischsten verfügbaren Modell',
    title1: 'Verwandle deine Selfies in', title2: 'Professionelle Headshots',
    subtitle: 'Lade 8–15 Fotos hoch. Wähle deinen Stil. Erhalte Headshots in Studioqualität in unter 30 Minuten — ohne Fotograf, Studio oder teure Sitzung.',
    ctaPrimary: 'Jetzt Headshots erstellen →', ctaSecondary: 'Preise ansehen',
    curious: '✨ Neugierig? Schau dich um — keine Anmeldung nötig', seeWomen: 'Frauen-Stile ansehen →', seeMen: 'Männer-Stile ansehen →',
    trust: ['Fertig in 30 Minuten', 'Profilwürdig-Garantie', '100% privat & sicher'], sliderBefore: 'Dein Selfie', sliderAfter: 'KI-Headshot',
  },
  valueBar: { delivery: 'Durchschnittliche Lieferzeit', styles: 'Einzigartige Stile verfügbar', startingPrice: 'Ab-Preis', guarantee: 'Profilwürdig-Garantie' },
  how: {
    heading: 'So funktioniert’s', sub: 'Drei einfache Schritte zu deinem perfekten Headshot', videoTitle: 'In 90 Sekunden sehen, wie es funktioniert', videoSoon: 'Video folgt in Kürze',
    steps: [
      { title: 'Lade deine Fotos hoch', desc: 'Lade 8–15 Selfies aus verschiedenen Winkeln und Lichtverhältnissen hoch. Keine professionelle Ausrüstung nötig.' },
      { title: 'Wähle deine Stile', desc: 'Wähle aus über 45 handverlesenen Stilen — Business, Casual, Kreativ, Outdoor, Restaurant und mehr. Jeder Stil erzeugt 4 einzigartige Varianten.' },
      { title: 'Erhalte deine Headshots', desc: 'Deine KI-Headshots sind in unter 30 Minuten fertig. Herunterladen und überall verwenden.' },
    ],
  },
  results: {
    heading: 'Echte Menschen. Echte Ergebnisse.', sub: 'Diese Headshots wurden mit Nova Imago erstellt. Kein Fotograf. Kein Studio.', before: 'Vorher', after: 'KI-Headshot', cta: 'Jetzt Headshots erstellen →',
    quotes: [
      'Ich konnte kaum glauben, wie realistisch es aussieht. Direkt auf LinkedIn verwendet!',
      'Unglaubliches Ergebnis — wirkt völlig natürlich und professionell.',
      'Die Qualität hat mich umgehauen. Perfekt für mein berufliches Profil!',
      'Absolut atemberaubende Ergebnisse. Sieht aus wie ich, nur noch besser!',
      'Fantastische Qualität — ich nutze es jetzt auf meinem LinkedIn-Profil!',
      'Die Ergebnisse haben meine Erwartungen übertroffen. So natürlich und professionell!',
    ],
  },
  features: {
    heading: 'Warum Profis uns wählen', sub: 'Studioqualität ohne den Studiopreis',
    items: [
      { title: 'Ergebnisse in 30 Minuten', desc: 'Lade deine Selfies hoch und erhalte professionelle Headshots in unter 30 Minuten. Kein tagelanges Warten auf einen Fotografen.' },
      { title: 'Über 45 kuratierte Stile', desc: 'Business Executive, Smart Casual, Kreativ, Outdoor, Restaurant und Date Night — feinabgestimmt für gleichbleibende Qualität. Jeder Stil erzeugt 4 einzigartige Varianten.' },
      { title: 'Angetrieben von FLUX AI', desc: 'Wir nutzen das fortschrittlichste verfügbare KI-Modell, speziell auf deine Fotos abgestimmt für maximalen Realismus.' },
      { title: 'Deine Fotos bleiben privat', desc: 'Deine Fotos werden verschlüsselt, niemals geteilt oder verkauft und nach Abschluss deiner Bestellung automatisch gelöscht.' },
      { title: 'Spare {sym}200–{sym}500', desc: 'Ein professioneller Fotograf berechnet {sym}300–{sym}700 für eine Sitzung. Erhalte unbegrenzte Varianten ab nur {sym}{p0}.' },
      { title: 'Profilwürdig-Garantie', desc: 'Wir garantieren mindestens 1 profilwürdigen Headshot in jeder Bestellung — oder Geld zurück innerhalb von 7 Tagen. Ohne Wenn und Aber.' },
    ],
  },
  pricing: {
    heading: 'Einfache, ehrliche Preise', sub: 'Einmalzahlung. Kein Abo. Keine versteckten Kosten.', note: 'Jeder Stil erzeugt 4 einzigartige Varianten.', oneTime: 'Einmalzahlung', bestValue: 'Beste Wahl', getStarted: 'Loslegen →', footnote: 'Einmalzahlung • Niemals ein Abo',
    tiers: [
      { name: 'Starter', line: '40 Headshots • 10 Stile', features: ['1 KI-Modell-Training', '40 HD-Headshots', 'Wähle 10 Stile × 4 Varianten', 'Über 45 Stile zur Auswahl', 'HD-Qualität', 'Fertig in 30 Minuten'] },
      { name: 'Pro', line: '80 Headshots • 20 Stile', features: ['1 KI-Modell-Training', '80 HD-Headshots', 'Wähle 20 Stile × 4 Varianten', 'Über 45 Stile zur Auswahl', 'HD-Qualität', 'Fertig in 30 Minuten'] },
      { name: 'Premium', line: '120 Headshots • 30 Stile', features: ['2 KI-Modell-Trainings', '120 HD-Headshots', 'Wähle 30 Stile × 4 Varianten', 'Über 45 Stile zur Auswahl', 'HD-Qualität', 'Fertig in 30 Minuten'] },
    ],
    guarantee: { title: 'Profilwürdig-Garantie', body: 'Nicht jedes Foto wird perfekt sein — das liegt in der Natur der KI. Aber wir garantieren mindestens 1 profilwürdigen Headshot in jeder Bestellung. Falls nicht, erstatten wir dir innerhalb von 7 Tagen den vollen Betrag. Keine Formulare, kein Aufwand.', items: ['Volle Rückerstattung innerhalb von 7 Tagen', 'Ohne Rückfragen', 'Keine Formulare, kein Aufwand'] },
  },
  faq: {
    heading: 'Häufige Fragen',
    items: [
      { q: 'Wie realistisch sind die KI-Headshots?', a: 'Wir nutzen FLUX LoRA — das fortschrittlichste KI-Porträtmodell. Die KI wird speziell auf deine Fotos trainiert, sodass die Ergebnisse wie du aussehen, nicht wie eine generische KI-Person.' },
      { q: 'Welche Fotos soll ich hochladen?', a: 'Lade 8–15 klare Einzelfotos mit gutem Licht aus verschiedenen Winkeln hoch. Vermeide Gruppenfotos, Sonnenbrillen, starke Filter oder unscharfe Bilder. Je mehr Vielfalt, desto besser das Ergebnis.' },
      { q: 'Wie lange dauert es?', a: 'Das Training deines persönlichen KI-Modells dauert etwa 20–25 Minuten. Danach erzeugt jeder Stil 4 Varianten in etwa 30 Sekunden.' },
      { q: 'Sind meine Fotos sicher?', a: 'Ja. Deine Fotos werden sicher gespeichert, niemals an Dritte weitergegeben und nach Abschluss deiner Bestellung automatisch gelöscht.' },
      { q: 'Was, wenn ich nicht zufrieden bin?', a: 'Wir garantieren mindestens 1 profilwürdigen Headshot in jeder Bestellung. Falls nicht, volle Rückerstattung innerhalb von 7 Tagen. Kein Aufwand — kontaktiere uns einfach.' },
      { q: 'Darf ich die Headshots kommerziell nutzen?', a: 'Ja. Du besitzt die Rechte an jedem Headshot, den wir für dich erstellen. Nutze sie auf LinkedIn, deiner Website, Visitenkarten oder überall sonst.' },
    ],
  },
  finalCta: { heading: 'Dein bestes Foto ist nur einen Upload entfernt', sub: 'Kein Fotograf. Kein Studio. Kein unangenehmes Posieren. Lade einfach deine Selfies hoch und lass die KI die Arbeit machen.', cta: 'Loslegen — ab {sym}{p0} →', badge: 'Profilwürdig-Garantie • Ohne Risiko' },
  footer: {
    product: 'Produkt', company: 'Unternehmen', useCases: 'Anwendungen', legal: 'Rechtliches', about: 'Über uns', contact: 'Kontakt', rights: '© 2026 Nova Imago • Alle Rechte vorbehalten',
    productItems: ['Funktionen', 'Preise', 'So funktioniert’s', 'FAQ'], useCaseItems: ['LinkedIn-Headshots', 'Bewerbungsfotos', 'Dating-Profil', 'Business-Porträts'], legalItems: ['Nutzungsbedingungen', 'Datenschutz', 'Rückerstattung', 'Cookie-Richtlinie'],
  },
}

const es: LandingCopy = {
  nav: { browseStyles: 'Ver estilos', whyUs: 'Por qué nosotros', plans: 'Precios', howItWorks: 'Cómo funciona', help: 'Ayuda', login: 'Iniciar sesión', getStarted: 'Empezar →', dashboard: 'Panel →' },
  hero: {
    badge: 'Con la tecnología de FLUX AI — el modelo más realista disponible',
    title1: 'Convierte tus selfies en', title2: 'Retratos profesionales',
    subtitle: 'Sube de 8 a 15 fotos. Elige tu estilo. Consigue retratos con calidad de estudio en menos de 30 minutos — sin fotógrafo, estudio ni sesiones caras.',
    ctaPrimary: 'Consigue tus retratos →', ctaSecondary: 'Ver precios',
    curious: '✨ ¿Con curiosidad? Echa un vistazo — sin registro', seeWomen: 'Ver estilos de mujer →', seeMen: 'Ver estilos de hombre →',
    trust: ['Listo en 30 minutos', 'Garantía apta para perfil', '100% privado y seguro'], sliderBefore: 'Tu selfie', sliderAfter: 'Retrato IA',
  },
  valueBar: { delivery: 'Tiempo medio de entrega', styles: 'Estilos únicos disponibles', startingPrice: 'Precio desde', guarantee: 'Garantía apta para perfil' },
  how: {
    heading: 'Cómo funciona', sub: 'Tres sencillos pasos hacia tu retrato perfecto', videoTitle: 'Descubre cómo funciona en 90 segundos', videoSoon: 'Vídeo próximamente',
    steps: [
      { title: 'Sube tus fotos', desc: 'Sube de 8 a 15 selfies desde distintos ángulos y condiciones de luz. No hace falta equipo profesional.' },
      { title: 'Elige tus estilos', desc: 'Elige entre más de 45 estilos cuidados — corporativo, casual, creativo, exterior, restaurante y más. Cada estilo genera 4 variaciones únicas.' },
      { title: 'Recibe tus retratos', desc: 'Tus retratos generados por IA están listos en menos de 30 minutos. Descárgalos y úsalos donde quieras.' },
    ],
  },
  results: {
    heading: 'Personas reales. Resultados reales.', sub: 'Estos retratos se generaron con Nova Imago. Sin fotógrafo. Sin estudio.', before: 'Antes', after: 'Retrato IA', cta: 'Consigue tus retratos →',
    quotes: [
      'No podía creer lo realista que se ve. ¡Ya lo estoy usando en LinkedIn!',
      'Resultado increíble — se ve totalmente natural y profesional.',
      '¡La calidad me impresionó. Perfecto para mi perfil profesional!',
      '¡Resultados absolutamente espectaculares. Soy yo, pero aún mejor!',
      '¡Calidad increíble — ahora lo uso en mi perfil de LinkedIn!',
      '¡Los resultados superaron mis expectativas. Tan natural y profesional!',
    ],
  },
  features: {
    heading: 'Por qué los profesionales nos eligen', sub: 'Calidad de estudio sin el precio del estudio',
    items: [
      { title: 'Resultados en 30 minutos', desc: 'Sube tus selfies y recibe retratos profesionales en menos de 30 minutos. Sin esperar días a un fotógrafo.' },
      { title: 'Más de 45 estilos cuidados', desc: 'Ejecutivo corporativo, smart casual, creativo, exterior, restaurante y date night — ajustados para una calidad constante. Cada estilo produce 4 variaciones únicas.' },
      { title: 'Con la tecnología de FLUX AI', desc: 'Usamos el modelo de IA más avanzado disponible, ajustado específicamente a tus fotos para un realismo máximo.' },
      { title: 'Tus fotos siguen privadas', desc: 'Tus fotos se cifran, nunca se comparten ni se venden, y se eliminan automáticamente al completar tu pedido.' },
      { title: 'Ahorra {sym}200–{sym}500', desc: 'Un fotógrafo profesional cobra {sym}300–{sym}700 por una sesión. Consigue variaciones ilimitadas desde solo {sym}{p0}.' },
      { title: 'Garantía apta para perfil', desc: 'Garantizamos al menos 1 retrato apto para perfil en cada pedido — o te devolvemos el dinero en 7 días. Sin preguntas.' },
    ],
  },
  pricing: {
    heading: 'Precios simples y honestos', sub: 'Pago único. Sin suscripciones. Sin costes ocultos.', note: 'Cada estilo genera 4 variaciones únicas.', oneTime: 'Pago único', bestValue: 'Mejor opción', getStarted: 'Empezar →', footnote: 'Pago único • Nunca una suscripción',
    tiers: [
      { name: 'Starter', line: '40 retratos • 10 estilos', features: ['1 entrenamiento de modelo IA', '40 retratos HD', 'Elige 10 estilos × 4 variaciones', 'Más de 45 estilos para elegir', 'Calidad HD', 'Listo en 30 minutos'] },
      { name: 'Pro', line: '80 retratos • 20 estilos', features: ['1 entrenamiento de modelo IA', '80 retratos HD', 'Elige 20 estilos × 4 variaciones', 'Más de 45 estilos para elegir', 'Calidad HD', 'Listo en 30 minutos'] },
      { name: 'Premium', line: '120 retratos • 30 estilos', features: ['2 entrenamientos de modelo IA', '120 retratos HD', 'Elige 30 estilos × 4 variaciones', 'Más de 45 estilos para elegir', 'Calidad HD', 'Listo en 30 minutos'] },
    ],
    guarantee: { title: 'Garantía apta para perfil', body: 'No todas las fotos serán perfectas — es la naturaleza de la IA. Pero garantizamos al menos 1 retrato apto para perfil en cada pedido. Si no, te reembolsamos por completo en 7 días. Sin formularios, sin complicaciones.', items: ['Reembolso completo en 7 días', 'Sin preguntas', 'Sin formularios ni complicaciones'] },
  },
  faq: {
    heading: 'Preguntas frecuentes',
    items: [
      { q: '¿Qué tan realistas son los retratos de IA?', a: 'Usamos FLUX LoRA — el modelo de retrato con IA más avanzado. La IA se entrena específicamente con tus fotos, por lo que los resultados se parecen a ti, no a una persona de IA genérica.' },
      { q: '¿Qué fotos debo subir?', a: 'Sube de 8 a 15 fotos individuales nítidas, con buena luz y desde distintos ángulos. Evita fotos de grupo, gafas de sol, filtros fuertes o imágenes borrosas. Cuanta más variedad, mejor el resultado.' },
      { q: '¿Cuánto tarda?', a: 'Entrenar tu modelo de IA personal tarda unos 20–25 minutos. Después, cada estilo genera 4 variaciones en unos 30 segundos.' },
      { q: '¿Están seguras mis fotos?', a: 'Sí. Tus fotos se almacenan de forma segura, nunca se comparten con terceros y se eliminan automáticamente al completar tu pedido.' },
      { q: '¿Y si no estoy satisfecho?', a: 'Garantizamos al menos 1 retrato apto para perfil en cada pedido. Si no, reembolso completo en 7 días. Sin complicaciones — solo contáctanos.' },
      { q: '¿Puedo usar estos retratos comercialmente?', a: 'Sí. Eres dueño de los derechos de cada retrato que generamos para ti. Úsalos en LinkedIn, tu web, tarjetas de visita o donde quieras.' },
    ],
  },
  finalCta: { heading: 'Tu mejor foto está a un solo clic', sub: 'Sin fotógrafo. Sin estudio. Sin poses incómodas. Solo sube tus selfies y deja que la IA haga el trabajo.', cta: 'Empezar — desde {sym}{p0} →', badge: 'Garantía apta para perfil • Sin riesgo' },
  footer: {
    product: 'Producto', company: 'Empresa', useCases: 'Casos de uso', legal: 'Legal', about: 'Sobre nosotros', contact: 'Contacto', rights: '© 2026 Nova Imago • Todos los derechos reservados',
    productItems: ['Funciones', 'Precios', 'Cómo funciona', 'FAQ'], useCaseItems: ['Retratos de LinkedIn', 'Fotos de CV', 'Perfil de citas', 'Retratos de empresa'], legalItems: ['Términos de servicio', 'Política de privacidad', 'Política de reembolso', 'Política de cookies'],
  },
}

const it: LandingCopy = {
  nav: { browseStyles: 'Sfoglia gli stili', whyUs: 'Perché noi', plans: 'Prezzi', howItWorks: 'Come funziona', help: 'Aiuto', login: 'Accedi', getStarted: 'Inizia →', dashboard: 'Dashboard →' },
  hero: {
    badge: 'Basato su FLUX AI — il modello più realistico disponibile',
    title1: 'Trasforma i tuoi selfie in', title2: 'Ritratti professionali',
    subtitle: 'Carica 8–15 foto. Scegli il tuo stile. Ottieni ritratti di qualità da studio in meno di 30 minuti — senza fotografo, studio o sessioni costose.',
    ctaPrimary: 'Ottieni i tuoi ritratti →', ctaSecondary: 'Vedi i prezzi',
    curious: '✨ Curioso? Dai un’occhiata — senza registrazione', seeWomen: 'Vedi stili donna →', seeMen: 'Vedi stili uomo →',
    trust: ['Pronto in 30 minuti', 'Garanzia foto profilo', '100% privato e sicuro'], sliderBefore: 'Il tuo selfie', sliderAfter: 'Ritratto IA',
  },
  valueBar: { delivery: 'Tempo medio di consegna', styles: 'Stili unici disponibili', startingPrice: 'Prezzo da', guarantee: 'Garanzia foto profilo' },
  how: {
    heading: 'Come funziona', sub: 'Tre semplici passi verso il tuo ritratto perfetto', videoTitle: 'Guarda come funziona in 90 secondi', videoSoon: 'Video in arrivo',
    steps: [
      { title: 'Carica le tue foto', desc: 'Carica 8–15 selfie da diverse angolazioni e condizioni di luce. Nessuna attrezzatura professionale necessaria.' },
      { title: 'Scegli i tuoi stili', desc: 'Scegli tra oltre 45 stili curati — corporate, casual, creativo, outdoor, ristorante e altro. Ogni stile genera 4 variazioni uniche.' },
      { title: 'Ricevi i tuoi ritratti', desc: 'I tuoi ritratti generati dall’IA sono pronti in meno di 30 minuti. Scaricali e usali ovunque.' },
    ],
  },
  results: {
    heading: 'Persone vere. Risultati veri.', sub: 'Questi ritratti sono stati generati con Nova Imago. Senza fotografo. Senza studio.', before: 'Prima', after: 'Ritratto IA', cta: 'Ottieni i tuoi ritratti →',
    quotes: [
      'Non credevo fosse così realistico. Lo uso subito su LinkedIn!',
      'Risultato incredibile — sembra del tutto naturale e professionale.',
      'La qualità mi ha stupito. Perfetto per il mio profilo professionale!',
      'Risultati assolutamente splendidi. Sono io, ma ancora meglio!',
      'Qualità pazzesca — ora lo uso sul mio profilo LinkedIn!',
      'I risultati hanno superato le mie aspettative. Così naturale e professionale!',
    ],
  },
  features: {
    heading: 'Perché i professionisti scelgono noi', sub: 'Qualità da studio senza il prezzo dello studio',
    items: [
      { title: 'Risultati in 30 minuti', desc: 'Carica i tuoi selfie e ricevi ritratti professionali in meno di 30 minuti. Niente giorni di attesa per un fotografo.' },
      { title: 'Oltre 45 stili curati', desc: 'Corporate executive, smart casual, creativo, outdoor, ristorante e date night — perfezionati per una qualità costante. Ogni stile produce 4 variazioni uniche.' },
      { title: 'Basato su FLUX AI', desc: 'Usiamo il modello di IA più avanzato disponibile, ottimizzato specificamente sulle tue foto per il massimo realismo.' },
      { title: 'Le tue foto restano private', desc: 'Le tue foto sono crittografate, mai condivise o vendute, ed eliminate automaticamente al completamento dell’ordine.' },
      { title: 'Risparmia {sym}200–{sym}500', desc: 'Un fotografo professionista chiede {sym}300–{sym}700 per una sessione. Ottieni variazioni illimitate a partire da soli {sym}{p0}.' },
      { title: 'Garanzia foto profilo', desc: 'Garantiamo almeno 1 ritratto adatto al profilo in ogni ordine — o rimborso entro 7 giorni. Senza domande.' },
    ],
  },
  pricing: {
    heading: 'Prezzi semplici e onesti', sub: 'Pagamento unico. Nessun abbonamento. Nessun costo nascosto.', note: 'Ogni stile genera 4 variazioni uniche.', oneTime: 'Pagamento unico', bestValue: 'Scelta migliore', getStarted: 'Inizia →', footnote: 'Pagamento unico • Mai un abbonamento',
    tiers: [
      { name: 'Starter', line: '40 ritratti • 10 stili', features: ['1 addestramento modello IA', '40 ritratti HD', 'Scegli 10 stili × 4 variazioni', 'Oltre 45 stili tra cui scegliere', 'Qualità HD', 'Pronto in 30 minuti'] },
      { name: 'Pro', line: '80 ritratti • 20 stili', features: ['1 addestramento modello IA', '80 ritratti HD', 'Scegli 20 stili × 4 variazioni', 'Oltre 45 stili tra cui scegliere', 'Qualità HD', 'Pronto in 30 minuti'] },
      { name: 'Premium', line: '120 ritratti • 30 stili', features: ['2 addestramenti modello IA', '120 ritratti HD', 'Scegli 30 stili × 4 variazioni', 'Oltre 45 stili tra cui scegliere', 'Qualità HD', 'Pronto in 30 minuti'] },
    ],
    guarantee: { title: 'Garanzia foto profilo', body: 'Non tutte le foto saranno perfette — è la natura dell’IA. Ma garantiamo almeno 1 ritratto adatto al profilo in ogni ordine. In caso contrario, ti rimborsiamo per intero entro 7 giorni. Senza moduli, senza problemi.', items: ['Rimborso completo entro 7 giorni', 'Senza domande', 'Senza moduli né problemi'] },
  },
  faq: {
    heading: 'Domande frequenti',
    items: [
      { q: 'Quanto sono realistici i ritratti IA?', a: 'Usiamo FLUX LoRA — il modello di ritratto IA più avanzato. L’IA è addestrata specificamente sulle tue foto, quindi i risultati assomigliano a te, non a una persona IA generica.' },
      { q: 'Che foto devo caricare?', a: 'Carica 8–15 foto singole nitide, ben illuminate e da diverse angolazioni. Evita foto di gruppo, occhiali da sole, filtri pesanti o immagini sfocate. Più varietà, migliore il risultato.' },
      { q: 'Quanto tempo ci vuole?', a: 'L’addestramento del tuo modello IA personale richiede circa 20–25 minuti. Dopodiché, ogni stile genera 4 variazioni in circa 30 secondi.' },
      { q: 'Le mie foto sono al sicuro?', a: 'Sì. Le tue foto sono archiviate in modo sicuro, mai condivise con terzi ed eliminate automaticamente al completamento dell’ordine.' },
      { q: 'E se non sono soddisfatto?', a: 'Garantiamo almeno 1 ritratto adatto al profilo in ogni ordine. In caso contrario, rimborso completo entro 7 giorni. Senza problemi — basta contattarci.' },
      { q: 'Posso usare questi ritratti commercialmente?', a: 'Sì. Possiedi i diritti su ogni ritratto che generiamo per te. Usali su LinkedIn, sul tuo sito, sui biglietti da visita o ovunque.' },
    ],
  },
  finalCta: { heading: 'La tua foto migliore è a un solo caricamento', sub: 'Senza fotografo. Senza studio. Senza pose imbarazzanti. Carica i tuoi selfie e lascia fare all’IA.', cta: 'Inizia — da {sym}{p0} →', badge: 'Garanzia foto profilo • Zero rischi' },
  footer: {
    product: 'Prodotto', company: 'Azienda', useCases: 'Casi d’uso', legal: 'Note legali', about: 'Chi siamo', contact: 'Contatti', rights: '© 2026 Nova Imago • Tutti i diritti riservati',
    productItems: ['Funzionalità', 'Prezzi', 'Come funziona', 'FAQ'], useCaseItems: ['Ritratti LinkedIn', 'Foto per CV', 'Profilo di incontri', 'Ritratti aziendali'], legalItems: ['Termini di servizio', 'Informativa privacy', 'Politica di rimborso', 'Politica sui cookie'],
  },
}

const pt: LandingCopy = {
  nav: { browseStyles: 'Ver estilos', whyUs: 'Por que nós', plans: 'Preços', howItWorks: 'Como funciona', help: 'Ajuda', login: 'Entrar', getStarted: 'Começar →', dashboard: 'Painel →' },
  hero: {
    badge: 'Desenvolvido com FLUX AI — o modelo mais realista disponível',
    title1: 'Transforme suas selfies em', title2: 'Retratos profissionais',
    subtitle: 'Envie de 8 a 15 fotos. Escolha seu estilo. Tenha retratos com qualidade de estúdio em menos de 30 minutos — sem fotógrafo, estúdio ou sessões caras.',
    ctaPrimary: 'Obter meus retratos →', ctaSecondary: 'Ver preços',
    curious: '✨ Curioso? Dê uma olhada — sem cadastro', seeWomen: 'Ver estilos femininos →', seeMen: 'Ver estilos masculinos →',
    trust: ['Pronto em 30 minutos', 'Garantia digna de perfil', '100% privado e seguro'], sliderBefore: 'Sua selfie', sliderAfter: 'Retrato IA',
  },
  valueBar: { delivery: 'Tempo médio de entrega', styles: 'Estilos únicos disponíveis', startingPrice: 'Preço a partir de', guarantee: 'Garantia digna de perfil' },
  how: {
    heading: 'Como funciona', sub: 'Três passos simples para o seu retrato perfeito', videoTitle: 'Veja como funciona em 90 segundos', videoSoon: 'Vídeo em breve',
    steps: [
      { title: 'Envie suas fotos', desc: 'Envie de 8 a 15 selfies de diferentes ângulos e condições de luz. Nenhum equipamento profissional necessário.' },
      { title: 'Escolha seus estilos', desc: 'Escolha entre mais de 45 estilos selecionados — corporativo, casual, criativo, ao ar livre, restaurante e mais. Cada estilo gera 4 variações únicas.' },
      { title: 'Receba seus retratos', desc: 'Seus retratos gerados por IA ficam prontos em menos de 30 minutos. Baixe e use onde quiser.' },
    ],
  },
  results: {
    heading: 'Pessoas reais. Resultados reais.', sub: 'Estes retratos foram gerados com o Nova Imago. Sem fotógrafo. Sem estúdio.', before: 'Antes', after: 'Retrato IA', cta: 'Obter meus retratos →',
    quotes: [
      'Não acreditei em como ficou realista. Já estou usando no LinkedIn!',
      'Resultado incrível — parece totalmente natural e profissional.',
      'A qualidade me impressionou. Perfeito para o meu perfil profissional!',
      'Resultados absolutamente incríveis. Sou eu, mas ainda melhor!',
      'Qualidade incrível — agora uso no meu perfil do LinkedIn!',
      'Os resultados superaram minhas expectativas. Tão natural e profissional!',
    ],
  },
  features: {
    heading: 'Por que os profissionais escolhem a gente', sub: 'Qualidade de estúdio sem o preço do estúdio',
    items: [
      { title: 'Resultados em 30 minutos', desc: 'Envie suas selfies e receba retratos profissionais em menos de 30 minutos. Sem esperar dias por um fotógrafo.' },
      { title: 'Mais de 45 estilos selecionados', desc: 'Executivo corporativo, smart casual, criativo, ao ar livre, restaurante e date night — ajustados para qualidade consistente. Cada estilo produz 4 variações únicas.' },
      { title: 'Desenvolvido com FLUX AI', desc: 'Usamos o modelo de IA mais avançado disponível, ajustado especificamente às suas fotos para o máximo de realismo.' },
      { title: 'Suas fotos ficam privadas', desc: 'Suas fotos são criptografadas, nunca compartilhadas ou vendidas, e excluídas automaticamente após a conclusão do pedido.' },
      { title: 'Economize {sym}200–{sym}500', desc: 'Um fotógrafo profissional cobra {sym}300–{sym}700 por uma sessão. Tenha variações ilimitadas a partir de apenas {sym}{p0}.' },
      { title: 'Garantia digna de perfil', desc: 'Garantimos pelo menos 1 retrato digno de perfil em cada pedido — ou seu dinheiro de volta em 7 dias. Sem perguntas.' },
    ],
  },
  pricing: {
    heading: 'Preços simples e honestos', sub: 'Pagamento único. Sem assinaturas. Sem taxas ocultas.', note: 'Cada estilo gera 4 variações únicas.', oneTime: 'Pagamento único', bestValue: 'Melhor escolha', getStarted: 'Começar →', footnote: 'Pagamento único • Nunca uma assinatura',
    tiers: [
      { name: 'Starter', line: '40 retratos • 10 estilos', features: ['1 treinamento de modelo IA', '40 retratos HD', 'Escolha 10 estilos × 4 variações', 'Mais de 45 estilos para escolher', 'Qualidade HD', 'Pronto em 30 minutos'] },
      { name: 'Pro', line: '80 retratos • 20 estilos', features: ['1 treinamento de modelo IA', '80 retratos HD', 'Escolha 20 estilos × 4 variações', 'Mais de 45 estilos para escolher', 'Qualidade HD', 'Pronto em 30 minutos'] },
      { name: 'Premium', line: '120 retratos • 30 estilos', features: ['2 treinamentos de modelo IA', '120 retratos HD', 'Escolha 30 estilos × 4 variações', 'Mais de 45 estilos para escolher', 'Qualidade HD', 'Pronto em 30 minutos'] },
    ],
    guarantee: { title: 'Garantia digna de perfil', body: 'Nem toda foto será perfeita — é a natureza da IA. Mas garantimos pelo menos 1 retrato digno de perfil em cada pedido. Caso contrário, reembolsamos integralmente em 7 dias. Sem formulários, sem complicação.', items: ['Reembolso total em 7 dias', 'Sem perguntas', 'Sem formulários nem complicação'] },
  },
  faq: {
    heading: 'Perguntas frequentes',
    items: [
      { q: 'Quão realistas são os retratos de IA?', a: 'Usamos FLUX LoRA — o modelo de retrato com IA mais avançado. A IA é treinada especificamente com as suas fotos, então os resultados se parecem com você, e não com uma pessoa de IA genérica.' },
      { q: 'Que fotos devo enviar?', a: 'Envie de 8 a 15 fotos individuais nítidas, com boa iluminação e de diferentes ângulos. Evite fotos em grupo, óculos de sol, filtros pesados ou imagens borradas. Quanto mais variedade, melhor o resultado.' },
      { q: 'Quanto tempo leva?', a: 'Treinar o seu modelo de IA pessoal leva cerca de 20–25 minutos. Depois disso, cada estilo gera 4 variações em cerca de 30 segundos.' },
      { q: 'Minhas fotos estão seguras?', a: 'Sim. Suas fotos são armazenadas com segurança, nunca compartilhadas com terceiros e excluídas automaticamente após a conclusão do pedido.' },
      { q: 'E se eu não gostar do resultado?', a: 'Garantimos pelo menos 1 retrato digno de perfil em cada pedido. Caso contrário, reembolso integral em 7 dias. Sem complicação — é só entrar em contato.' },
      { q: 'Posso usar estes retratos comercialmente?', a: 'Sim. Você detém os direitos de cada retrato que geramos para você. Use-os no LinkedIn, no seu site, em cartões de visita ou onde quiser.' },
    ],
  },
  finalCta: { heading: 'A sua melhor foto está a um upload de distância', sub: 'Sem fotógrafo. Sem estúdio. Sem poses constrangedoras. Basta enviar suas selfies e deixar a IA trabalhar.', cta: 'Começar — a partir de {sym}{p0} →', badge: 'Garantia digna de perfil • Sem risco' },
  footer: {
    product: 'Produto', company: 'Empresa', useCases: 'Casos de uso', legal: 'Jurídico', about: 'Sobre nós', contact: 'Contato', rights: '© 2026 Nova Imago • Todos os direitos reservados',
    productItems: ['Recursos', 'Preços', 'Como funciona', 'FAQ'], useCaseItems: ['Retratos LinkedIn', 'Fotos de currículo', 'Perfil de namoro', 'Retratos corporativos'], legalItems: ['Termos de serviço', 'Política de privacidade', 'Política de reembolso', 'Política de cookies'],
  },
}

export const LANDING: Record<Locale, LandingCopy> = { en, nl, fr, de, es, it, pt }
