import type { Locale } from '@/lib/i18n'

// Vertaling van categorie-namen + stijl-beschrijvingen (sleutel = Engelse brontekst).
// Stijl-namen (labels) blijven bewust Engels (do-not-translate, best practice).
// Herhaalde beschrijvingen worden zo maar één keer vertaald.

const nl: Record<string, string> = {
  // Categorieën
  'Formal / Corporate Power': 'Formeel / Corporate Power', 'Smart Casual / Business Modern': 'Smart Casual / Zakelijk Modern', 'Restaurant / Date Night': 'Restaurant / Date Night', 'Tech Founder / Sweater': 'Tech Founder / Trui', 'Casual Professional': 'Casual Professioneel', 'Outdoor / Lifestyle': 'Outdoor / Lifestyle', 'Travel / Adventure': 'Reizen / Avontuur', 'Creative / Bold': 'Creatief / Gedurfd', 'Specialty Poses': 'Speciale poses', 'Casual / Approachable': 'Casual / Toegankelijk', 'Evening / Statement': 'Avond / Statement',
  // Beschrijvingen — mannen
  'Navy suit, modern office': 'Marineblauw pak, modern kantoor', 'Navy suit, city skyline': 'Marineblauw pak, skyline', 'Black suit, dramatic dark bg': 'Zwart pak, donkere achtergrond', 'Light grey suit, premium office': 'Lichtgrijs pak, premium kantoor', 'Pinstripe suit + tie': 'Krijtstreeppak + das', 'Three piece suit + vest': 'Driedelig pak + gilet', 'Black suit, dramatic light': 'Zwart pak, dramatisch licht', 'Dark suit, red tie, skyscrapers': 'Donker pak, rode das, wolkenkrabbers',
  'Navy blazer, open collar': 'Marineblauwe blazer, open kraag', 'Gray blazer, blue bg': 'Grijze blazer, blauwe achtergrond', 'Beige linen suit': 'Beige linnen pak', 'Teal blazer, white tee': 'Petrol blazer, wit T-shirt', 'Light blue blazer, office': 'Lichtblauwe blazer, kantoor', 'Black blazer + turtleneck': 'Zwarte blazer + coltrui', 'Light gray suit, no tie': 'Lichtgrijs pak, zonder das',
  'Upscale restaurant, candlelit': 'Chic restaurant, bij kaarslicht', 'At wine bar, warm light': 'In wijnbar, warm licht', 'Coffee shop, ambient': 'Koffiebar, sfeervol', 'City lights, evening': 'Stadslichten, avond',
  'Gray turtleneck, minimal': 'Grijze coltrui, minimalistisch', 'Crew neck over collar': 'Ronde hals over kraag', 'Chunky knit, warm light': 'Grove gebreide trui, warm licht', 'Blue V-neck over collar': 'Blauwe V-hals over kraag',
  'Clean white shirt': 'Strak wit hemd', 'Light blue oxford, open': 'Lichtblauw oxford-hemd, open', 'Navy polo, clean bg': 'Marineblauwe polo, strakke achtergrond', 'Chambray, white bg': 'Chambray, witte achtergrond', 'Plaid button-up, neutral': 'Geruit hemd, neutraal', 'Plain white tee, casual': 'Effen wit T-shirt, casual', 'Plain black tee, casual': 'Effen zwart T-shirt, casual', 'Henley, warm window light': 'Henley, warm raamlicht',
  'Warm tones, sunset light': 'Warme tinten, avondlicht', 'Green park, daylight': 'Groen park, daglicht', 'City skyline, rooftop': 'Skyline, dakterras', 'Walking, urban street': 'Wandelend, stadsstraat',
  'White linen, sunglasses, beach': 'Wit linnen, zonnebril, strand', 'Winter jacket, snowy peaks': 'Winterjas, besneeuwde toppen', 'Luxury pool, sunny vacation': 'Luxe zwembad, zonnige vakantie', 'Sweater, golden fall foliage': 'Trui, gouden herfstbladeren', 'Outdoor jacket, scenic lake': 'Outdoor-jas, mooi meer',
  'Black leather, urban': 'Zwart leer, urban', 'All black, dramatic': 'Volledig zwart, dramatisch', 'Red/emerald blazer': 'Rode/smaragdgroene blazer', 'Leather jacket, motorbike': 'Leren jas, motor', 'Smart casual, classic car': 'Smart casual, klassieke auto',
  'Arms crossed, dark suit': 'Armen gekruist, donker pak', 'Seated at desk, engaging': 'Zittend aan bureau, betrokken', 'Leaning casual, outdoor': 'Casual leunend, buiten', 'Leaning, modern office': 'Leunend, modern kantoor', 'Relaxed, urban background': 'Ontspannen, stadsachtergrond', 'Hand near chin, intellectual': 'Hand bij kin, intellectueel', 'Tablet, modern office': 'Tablet, modern kantoor',
  // Beschrijvingen — vrouwen
  'Navy blazer, white blouse': 'Marineblauwe blazer, witte blouse', 'Charcoal suit, modern': 'Antracietkleurig pak, modern', 'Black blazer, powerful': 'Zwarte blazer, krachtig', 'Pinstripe blazer, silk': 'Krijtstreepblazer, zijde', 'Black sheath, refined': 'Zwarte kokerjurk, verfijnd', 'Silk blouse, tweed': 'Zijden blouse, tweed',
  'Cream blazer + tee': 'Crèmekleurige blazer + T-shirt', 'Black turtleneck + gray': 'Zwarte coltrui + grijs', 'Navy silk, modern office': 'Marineblauwe zijde, modern kantoor', 'Beige cardigan, warm': 'Beige vest, warm', 'Matching knit, neutral': 'Bijpassend gebreid, neutraal', 'Light blue shirt, modern': 'Lichtblauw hemd, modern',
  'Silk blouse, candlelit': 'Zijden blouse, bij kaarslicht', 'Cocktail dress, evening': 'Cocktailjurk, avond', 'Rooftop bar, city lights': 'Rooftopbar, stadslichten', 'Intimate, candlelight': 'Intiem, kaarslicht', 'Smart casual, bistro': 'Smart casual, bistro',
  'Red suit, statement': 'Rood pak, statement', 'Green blazer, bold': 'Groene blazer, gedurfd', 'Deep burgundy silk, bold': 'Diep bordeauxrode zijde, gedurfd', 'Cobalt blue, statement': 'Kobaltblauw, statement', 'Deep purple, expressive': 'Dieppaars, expressief',
  'White tee, green outdoor': 'Wit T-shirt, groen buiten', 'Soft knit, window light': 'Zacht gebreid, raamlicht', 'Chambray, fresh white bg': 'Chambray, frisse witte achtergrond', 'Casual sweater, café': 'Casual trui, café', 'Light blouse, park bg': 'Lichte blouse, park',
  'City panorama, golden hour': 'Stadspanorama, gouden uur', 'Modern architecture bg': 'Moderne architectuur',
  'Linen blouse, coastal': 'Linnen blouse, kust', 'With a horse, countryside': 'Met een paard, platteland',
  'Arms crossed, blazer': 'Armen gekruist, blazer', 'Relaxed pose, urban': 'Ontspannen pose, urban', 'Hand near chin, elegant': 'Hand bij kin, elegant',
  'Black leather, edgy': 'Zwart leer, edgy', 'Black evening top, lights': 'Zwarte avondtop, lichten', 'Elegant gown, black-tie gala': 'Elegante avondjurk, black-tie gala',
}

const fr: Record<string, string> = {
  'Formal / Corporate Power': 'Formel / Corporate', 'Smart Casual / Business Modern': 'Smart Casual / Business moderne', 'Restaurant / Date Night': 'Restaurant / Soirée', 'Tech Founder / Sweater': 'Tech Founder / Pull', 'Casual Professional': 'Décontracté pro', 'Outdoor / Lifestyle': 'Extérieur / Lifestyle', 'Travel / Adventure': 'Voyage / Aventure', 'Creative / Bold': 'Créatif / Audacieux', 'Specialty Poses': 'Poses spéciales', 'Casual / Approachable': 'Décontracté / Accessible', 'Evening / Statement': 'Soirée / Statement',
  'Navy suit, modern office': 'Costume marine, bureau moderne', 'Navy suit, city skyline': 'Costume marine, skyline', 'Black suit, dramatic dark bg': 'Costume noir, fond sombre', 'Light grey suit, premium office': 'Costume gris clair, bureau premium', 'Pinstripe suit + tie': 'Costume à rayures + cravate', 'Three piece suit + vest': 'Costume trois pièces + gilet', 'Black suit, dramatic light': 'Costume noir, lumière dramatique', 'Dark suit, red tie, skyscrapers': 'Costume sombre, cravate rouge, gratte-ciels',
  'Navy blazer, open collar': 'Blazer marine, col ouvert', 'Gray blazer, blue bg': 'Blazer gris, fond bleu', 'Beige linen suit': 'Costume en lin beige', 'Teal blazer, white tee': 'Blazer canard, t-shirt blanc', 'Light blue blazer, office': 'Blazer bleu clair, bureau', 'Black blazer + turtleneck': 'Blazer noir + col roulé', 'Light gray suit, no tie': 'Costume gris clair, sans cravate',
  'Upscale restaurant, candlelit': 'Restaurant chic, aux chandelles', 'At wine bar, warm light': 'Au bar à vin, lumière chaude', 'Coffee shop, ambient': 'Café, ambiance', 'City lights, evening': 'Lumières de la ville, soir',
  'Gray turtleneck, minimal': 'Col roulé gris, minimaliste', 'Crew neck over collar': 'Col rond sur chemise', 'Chunky knit, warm light': 'Grosse maille, lumière chaude', 'Blue V-neck over collar': 'Col V bleu sur chemise',
  'Clean white shirt': 'Chemise blanche nette', 'Light blue oxford, open': 'Oxford bleu clair, ouvert', 'Navy polo, clean bg': 'Polo marine, fond épuré', 'Chambray, white bg': 'Chambray, fond blanc', 'Plaid button-up, neutral': 'Chemise à carreaux, neutre', 'Plain white tee, casual': 'T-shirt blanc uni, décontracté', 'Plain black tee, casual': 'T-shirt noir uni, décontracté', 'Henley, warm window light': 'Henley, lumière chaude de fenêtre',
  'Warm tones, sunset light': 'Tons chauds, lumière de coucher', 'Green park, daylight': 'Parc verdoyant, jour', 'City skyline, rooftop': 'Skyline, rooftop', 'Walking, urban street': 'En marchant, rue urbaine',
  'White linen, sunglasses, beach': 'Lin blanc, lunettes, plage', 'Winter jacket, snowy peaks': 'Veste d’hiver, sommets enneigés', 'Luxury pool, sunny vacation': 'Piscine de luxe, vacances ensoleillées', 'Sweater, golden fall foliage': 'Pull, feuillage d’automne doré', 'Outdoor jacket, scenic lake': 'Veste outdoor, lac pittoresque',
  'Black leather, urban': 'Cuir noir, urbain', 'All black, dramatic': 'Tout en noir, dramatique', 'Red/emerald blazer': 'Blazer rouge/émeraude', 'Leather jacket, motorbike': 'Veste en cuir, moto', 'Smart casual, classic car': 'Smart casual, voiture classique',
  'Arms crossed, dark suit': 'Bras croisés, costume sombre', 'Seated at desk, engaging': 'Assis au bureau, engageant', 'Leaning casual, outdoor': 'Appuyé décontracté, extérieur', 'Leaning, modern office': 'Appuyé, bureau moderne', 'Relaxed, urban background': 'Détendu, fond urbain', 'Hand near chin, intellectual': 'Main près du menton, intellectuel', 'Tablet, modern office': 'Tablette, bureau moderne',
  'Navy blazer, white blouse': 'Blazer marine, chemisier blanc', 'Charcoal suit, modern': 'Tailleur anthracite, moderne', 'Black blazer, powerful': 'Blazer noir, puissant', 'Pinstripe blazer, silk': 'Blazer à rayures, soie', 'Black sheath, refined': 'Robe fourreau noire, raffinée', 'Silk blouse, tweed': 'Chemisier en soie, tweed',
  'Cream blazer + tee': 'Blazer crème + t-shirt', 'Black turtleneck + gray': 'Col roulé noir + gris', 'Navy silk, modern office': 'Soie marine, bureau moderne', 'Beige cardigan, warm': 'Cardigan beige, chaleureux', 'Matching knit, neutral': 'Maille assortie, neutre', 'Light blue shirt, modern': 'Chemise bleu clair, moderne',
  'Silk blouse, candlelit': 'Chemisier en soie, aux chandelles', 'Cocktail dress, evening': 'Robe de cocktail, soirée', 'Rooftop bar, city lights': 'Bar rooftop, lumières de la ville', 'Intimate, candlelight': 'Intime, aux chandelles', 'Smart casual, bistro': 'Smart casual, bistro',
  'Red suit, statement': 'Tailleur rouge, statement', 'Green blazer, bold': 'Blazer vert, audacieux', 'Deep burgundy silk, bold': 'Soie bordeaux profond, audacieux', 'Cobalt blue, statement': 'Bleu cobalt, statement', 'Deep purple, expressive': 'Violet profond, expressif',
  'White tee, green outdoor': 'T-shirt blanc, extérieur vert', 'Soft knit, window light': 'Maille douce, lumière de fenêtre', 'Chambray, fresh white bg': 'Chambray, fond blanc frais', 'Casual sweater, café': 'Pull décontracté, café', 'Light blouse, park bg': 'Blouse légère, parc',
  'City panorama, golden hour': 'Panorama urbain, golden hour', 'Modern architecture bg': 'Architecture moderne',
  'Linen blouse, coastal': 'Blouse en lin, bord de mer', 'With a horse, countryside': 'Avec un cheval, campagne',
  'Arms crossed, blazer': 'Bras croisés, blazer', 'Relaxed pose, urban': 'Pose détendue, urbain', 'Hand near chin, elegant': 'Main près du menton, élégant',
  'Black leather, edgy': 'Cuir noir, edgy', 'Black evening top, lights': 'Haut de soirée noir, lumières', 'Elegant gown, black-tie gala': 'Robe élégante, gala black-tie',
}

const de: Record<string, string> = {
  'Formal / Corporate Power': 'Formell / Corporate', 'Smart Casual / Business Modern': 'Smart Casual / Business modern', 'Restaurant / Date Night': 'Restaurant / Date Night', 'Tech Founder / Sweater': 'Tech Founder / Pullover', 'Casual Professional': 'Casual professionell', 'Outdoor / Lifestyle': 'Outdoor / Lifestyle', 'Travel / Adventure': 'Reisen / Abenteuer', 'Creative / Bold': 'Kreativ / Mutig', 'Specialty Poses': 'Besondere Posen', 'Casual / Approachable': 'Casual / Nahbar', 'Evening / Statement': 'Abend / Statement',
  'Navy suit, modern office': 'Marineblauer Anzug, modernes Büro', 'Navy suit, city skyline': 'Marineblauer Anzug, Skyline', 'Black suit, dramatic dark bg': 'Schwarzer Anzug, dunkler Hintergrund', 'Light grey suit, premium office': 'Hellgrauer Anzug, Premium-Büro', 'Pinstripe suit + tie': 'Nadelstreifenanzug + Krawatte', 'Three piece suit + vest': 'Dreiteiliger Anzug + Weste', 'Black suit, dramatic light': 'Schwarzer Anzug, dramatisches Licht', 'Dark suit, red tie, skyscrapers': 'Dunkler Anzug, rote Krawatte, Wolkenkratzer',
  'Navy blazer, open collar': 'Marineblauer Blazer, offener Kragen', 'Gray blazer, blue bg': 'Grauer Blazer, blauer Hintergrund', 'Beige linen suit': 'Beiger Leinenanzug', 'Teal blazer, white tee': 'Petrol-Blazer, weißes Shirt', 'Light blue blazer, office': 'Hellblauer Blazer, Büro', 'Black blazer + turtleneck': 'Schwarzer Blazer + Rollkragen', 'Light gray suit, no tie': 'Hellgrauer Anzug, ohne Krawatte',
  'Upscale restaurant, candlelit': 'Gehobenes Restaurant, Kerzenlicht', 'At wine bar, warm light': 'In der Weinbar, warmes Licht', 'Coffee shop, ambient': 'Café, stimmungsvoll', 'City lights, evening': 'Stadtlichter, Abend',
  'Gray turtleneck, minimal': 'Grauer Rollkragen, minimalistisch', 'Crew neck over collar': 'Rundhals über Kragen', 'Chunky knit, warm light': 'Grobstrick, warmes Licht', 'Blue V-neck over collar': 'Blauer V-Ausschnitt über Kragen',
  'Clean white shirt': 'Klares weißes Hemd', 'Light blue oxford, open': 'Hellblaues Oxford, offen', 'Navy polo, clean bg': 'Marineblaues Polo, klarer Hintergrund', 'Chambray, white bg': 'Chambray, weißer Hintergrund', 'Plaid button-up, neutral': 'Kariertes Hemd, neutral', 'Plain white tee, casual': 'Schlichtes weißes Shirt, casual', 'Plain black tee, casual': 'Schlichtes schwarzes Shirt, casual', 'Henley, warm window light': 'Henley, warmes Fensterlicht',
  'Warm tones, sunset light': 'Warme Töne, Abendlicht', 'Green park, daylight': 'Grüner Park, Tageslicht', 'City skyline, rooftop': 'Skyline, Dachterrasse', 'Walking, urban street': 'Gehend, Stadtstraße',
  'White linen, sunglasses, beach': 'Weißes Leinen, Sonnenbrille, Strand', 'Winter jacket, snowy peaks': 'Winterjacke, verschneite Gipfel', 'Luxury pool, sunny vacation': 'Luxuspool, sonniger Urlaub', 'Sweater, golden fall foliage': 'Pullover, goldenes Herbstlaub', 'Outdoor jacket, scenic lake': 'Outdoor-Jacke, malerischer See',
  'Black leather, urban': 'Schwarzes Leder, urban', 'All black, dramatic': 'Ganz in Schwarz, dramatisch', 'Red/emerald blazer': 'Roter/smaragdgrüner Blazer', 'Leather jacket, motorbike': 'Lederjacke, Motorrad', 'Smart casual, classic car': 'Smart Casual, Oldtimer',
  'Arms crossed, dark suit': 'Arme verschränkt, dunkler Anzug', 'Seated at desk, engaging': 'Am Schreibtisch sitzend, einnehmend', 'Leaning casual, outdoor': 'Lässig angelehnt, draußen', 'Leaning, modern office': 'Angelehnt, modernes Büro', 'Relaxed, urban background': 'Entspannt, urbaner Hintergrund', 'Hand near chin, intellectual': 'Hand am Kinn, intellektuell', 'Tablet, modern office': 'Tablet, modernes Büro',
  'Navy blazer, white blouse': 'Marineblauer Blazer, weiße Bluse', 'Charcoal suit, modern': 'Anthrazitfarbenes Kostüm, modern', 'Black blazer, powerful': 'Schwarzer Blazer, kraftvoll', 'Pinstripe blazer, silk': 'Nadelstreifen-Blazer, Seide', 'Black sheath, refined': 'Schwarzes Etuikleid, edel', 'Silk blouse, tweed': 'Seidenbluse, Tweed',
  'Cream blazer + tee': 'Cremefarbener Blazer + Shirt', 'Black turtleneck + gray': 'Schwarzer Rollkragen + Grau', 'Navy silk, modern office': 'Marineblaue Seide, modernes Büro', 'Beige cardigan, warm': 'Beige Strickjacke, warm', 'Matching knit, neutral': 'Passender Strick, neutral', 'Light blue shirt, modern': 'Hellblaues Hemd, modern',
  'Silk blouse, candlelit': 'Seidenbluse, Kerzenlicht', 'Cocktail dress, evening': 'Cocktailkleid, Abend', 'Rooftop bar, city lights': 'Rooftop-Bar, Stadtlichter', 'Intimate, candlelight': 'Intim, Kerzenlicht', 'Smart casual, bistro': 'Smart Casual, Bistro',
  'Red suit, statement': 'Roter Anzug, Statement', 'Green blazer, bold': 'Grüner Blazer, mutig', 'Deep burgundy silk, bold': 'Tiefe bordeauxrote Seide, mutig', 'Cobalt blue, statement': 'Kobaltblau, Statement', 'Deep purple, expressive': 'Tiefes Violett, ausdrucksstark',
  'White tee, green outdoor': 'Weißes Shirt, grünes Outdoor', 'Soft knit, window light': 'Weicher Strick, Fensterlicht', 'Chambray, fresh white bg': 'Chambray, frischer weißer Hintergrund', 'Casual sweater, café': 'Lässiger Pullover, Café', 'Light blouse, park bg': 'Leichte Bluse, Park',
  'City panorama, golden hour': 'Stadtpanorama, Golden Hour', 'Modern architecture bg': 'Moderne Architektur',
  'Linen blouse, coastal': 'Leinenbluse, Küste', 'With a horse, countryside': 'Mit einem Pferd, Landschaft',
  'Arms crossed, blazer': 'Arme verschränkt, Blazer', 'Relaxed pose, urban': 'Entspannte Pose, urban', 'Hand near chin, elegant': 'Hand am Kinn, elegant',
  'Black leather, edgy': 'Schwarzes Leder, kantig', 'Black evening top, lights': 'Schwarzes Abendtop, Lichter', 'Elegant gown, black-tie gala': 'Elegante Robe, Black-Tie-Gala',
}

const es: Record<string, string> = {
  'Formal / Corporate Power': 'Formal / Corporativo', 'Smart Casual / Business Modern': 'Smart Casual / Business moderno', 'Restaurant / Date Night': 'Restaurante / Cita', 'Tech Founder / Sweater': 'Tech Founder / Jersey', 'Casual Professional': 'Casual profesional', 'Outdoor / Lifestyle': 'Exterior / Lifestyle', 'Travel / Adventure': 'Viajes / Aventura', 'Creative / Bold': 'Creativo / Atrevido', 'Specialty Poses': 'Poses especiales', 'Casual / Approachable': 'Casual / Cercano', 'Evening / Statement': 'Noche / Statement',
  'Navy suit, modern office': 'Traje azul marino, oficina moderna', 'Navy suit, city skyline': 'Traje azul marino, skyline', 'Black suit, dramatic dark bg': 'Traje negro, fondo oscuro', 'Light grey suit, premium office': 'Traje gris claro, oficina premium', 'Pinstripe suit + tie': 'Traje de raya diplomática + corbata', 'Three piece suit + vest': 'Traje de tres piezas + chaleco', 'Black suit, dramatic light': 'Traje negro, luz dramática', 'Dark suit, red tie, skyscrapers': 'Traje oscuro, corbata roja, rascacielos',
  'Navy blazer, open collar': 'Blazer azul marino, cuello abierto', 'Gray blazer, blue bg': 'Blazer gris, fondo azul', 'Beige linen suit': 'Traje de lino beige', 'Teal blazer, white tee': 'Blazer verde azulado, camiseta blanca', 'Light blue blazer, office': 'Blazer azul claro, oficina', 'Black blazer + turtleneck': 'Blazer negro + cuello alto', 'Light gray suit, no tie': 'Traje gris claro, sin corbata',
  'Upscale restaurant, candlelit': 'Restaurante elegante, con velas', 'At wine bar, warm light': 'En bar de vinos, luz cálida', 'Coffee shop, ambient': 'Cafetería, ambiente', 'City lights, evening': 'Luces de la ciudad, noche',
  'Gray turtleneck, minimal': 'Cuello alto gris, minimalista', 'Crew neck over collar': 'Cuello redondo sobre camisa', 'Chunky knit, warm light': 'Punto grueso, luz cálida', 'Blue V-neck over collar': 'Cuello de pico azul sobre camisa',
  'Clean white shirt': 'Camisa blanca impecable', 'Light blue oxford, open': 'Oxford azul claro, abierto', 'Navy polo, clean bg': 'Polo azul marino, fondo limpio', 'Chambray, white bg': 'Chambray, fondo blanco', 'Plaid button-up, neutral': 'Camisa de cuadros, neutra', 'Plain white tee, casual': 'Camiseta blanca lisa, casual', 'Plain black tee, casual': 'Camiseta negra lisa, casual', 'Henley, warm window light': 'Henley, luz cálida de ventana',
  'Warm tones, sunset light': 'Tonos cálidos, luz de atardecer', 'Green park, daylight': 'Parque verde, luz de día', 'City skyline, rooftop': 'Skyline, azotea', 'Walking, urban street': 'Caminando, calle urbana',
  'White linen, sunglasses, beach': 'Lino blanco, gafas de sol, playa', 'Winter jacket, snowy peaks': 'Chaqueta de invierno, picos nevados', 'Luxury pool, sunny vacation': 'Piscina de lujo, vacaciones soleadas', 'Sweater, golden fall foliage': 'Jersey, follaje otoñal dorado', 'Outdoor jacket, scenic lake': 'Chaqueta outdoor, lago pintoresco',
  'Black leather, urban': 'Cuero negro, urbano', 'All black, dramatic': 'Todo negro, dramático', 'Red/emerald blazer': 'Blazer rojo/esmeralda', 'Leather jacket, motorbike': 'Chaqueta de cuero, moto', 'Smart casual, classic car': 'Smart casual, coche clásico',
  'Arms crossed, dark suit': 'Brazos cruzados, traje oscuro', 'Seated at desk, engaging': 'Sentado en el escritorio, cercano', 'Leaning casual, outdoor': 'Apoyado casual, exterior', 'Leaning, modern office': 'Apoyado, oficina moderna', 'Relaxed, urban background': 'Relajado, fondo urbano', 'Hand near chin, intellectual': 'Mano cerca del mentón, intelectual', 'Tablet, modern office': 'Tableta, oficina moderna',
  'Navy blazer, white blouse': 'Blazer azul marino, blusa blanca', 'Charcoal suit, modern': 'Traje antracita, moderno', 'Black blazer, powerful': 'Blazer negro, poderoso', 'Pinstripe blazer, silk': 'Blazer de raya diplomática, seda', 'Black sheath, refined': 'Vestido tubo negro, refinado', 'Silk blouse, tweed': 'Blusa de seda, tweed',
  'Cream blazer + tee': 'Blazer crema + camiseta', 'Black turtleneck + gray': 'Cuello alto negro + gris', 'Navy silk, modern office': 'Seda azul marino, oficina moderna', 'Beige cardigan, warm': 'Cárdigan beige, cálido', 'Matching knit, neutral': 'Punto a juego, neutro', 'Light blue shirt, modern': 'Camisa azul claro, moderna',
  'Silk blouse, candlelit': 'Blusa de seda, con velas', 'Cocktail dress, evening': 'Vestido de cóctel, noche', 'Rooftop bar, city lights': 'Bar en azotea, luces de la ciudad', 'Intimate, candlelight': 'Íntimo, luz de velas', 'Smart casual, bistro': 'Smart casual, bistró',
  'Red suit, statement': 'Traje rojo, statement', 'Green blazer, bold': 'Blazer verde, atrevido', 'Deep burgundy silk, bold': 'Seda burdeos profundo, atrevido', 'Cobalt blue, statement': 'Azul cobalto, statement', 'Deep purple, expressive': 'Púrpura profundo, expresivo',
  'White tee, green outdoor': 'Camiseta blanca, exterior verde', 'Soft knit, window light': 'Punto suave, luz de ventana', 'Chambray, fresh white bg': 'Chambray, fondo blanco fresco', 'Casual sweater, café': 'Jersey casual, café', 'Light blouse, park bg': 'Blusa ligera, parque',
  'City panorama, golden hour': 'Panorama urbano, hora dorada', 'Modern architecture bg': 'Arquitectura moderna',
  'Linen blouse, coastal': 'Blusa de lino, costa', 'With a horse, countryside': 'Con un caballo, campo',
  'Arms crossed, blazer': 'Brazos cruzados, blazer', 'Relaxed pose, urban': 'Pose relajada, urbano', 'Hand near chin, elegant': 'Mano cerca del mentón, elegante',
  'Black leather, edgy': 'Cuero negro, atrevido', 'Black evening top, lights': 'Top de noche negro, luces', 'Elegant gown, black-tie gala': 'Vestido elegante, gala de etiqueta',
}

const it: Record<string, string> = {
  'Formal / Corporate Power': 'Formale / Corporate', 'Smart Casual / Business Modern': 'Smart Casual / Business moderno', 'Restaurant / Date Night': 'Ristorante / Serata', 'Tech Founder / Sweater': 'Tech Founder / Maglione', 'Casual Professional': 'Casual professionale', 'Outdoor / Lifestyle': 'Outdoor / Lifestyle', 'Travel / Adventure': 'Viaggi / Avventura', 'Creative / Bold': 'Creativo / Audace', 'Specialty Poses': 'Pose speciali', 'Casual / Approachable': 'Casual / Accessibile', 'Evening / Statement': 'Sera / Statement',
  'Navy suit, modern office': 'Completo blu, ufficio moderno', 'Navy suit, city skyline': 'Completo blu, skyline', 'Black suit, dramatic dark bg': 'Completo nero, sfondo scuro', 'Light grey suit, premium office': 'Completo grigio chiaro, ufficio premium', 'Pinstripe suit + tie': 'Completo gessato + cravatta', 'Three piece suit + vest': 'Completo tre pezzi + gilet', 'Black suit, dramatic light': 'Completo nero, luce drammatica', 'Dark suit, red tie, skyscrapers': 'Completo scuro, cravatta rossa, grattacieli',
  'Navy blazer, open collar': 'Blazer blu, colletto aperto', 'Gray blazer, blue bg': 'Blazer grigio, sfondo blu', 'Beige linen suit': 'Completo di lino beige', 'Teal blazer, white tee': 'Blazer verde-azzurro, t-shirt bianca', 'Light blue blazer, office': 'Blazer azzurro, ufficio', 'Black blazer + turtleneck': 'Blazer nero + dolcevita', 'Light gray suit, no tie': 'Completo grigio chiaro, senza cravatta',
  'Upscale restaurant, candlelit': 'Ristorante elegante, a lume di candela', 'At wine bar, warm light': 'Al wine bar, luce calda', 'Coffee shop, ambient': 'Caffetteria, atmosfera', 'City lights, evening': 'Luci della città, sera',
  'Gray turtleneck, minimal': 'Dolcevita grigio, minimal', 'Crew neck over collar': 'Girocollo sopra camicia', 'Chunky knit, warm light': 'Maglia grossa, luce calda', 'Blue V-neck over collar': 'Scollo a V blu sopra camicia',
  'Clean white shirt': 'Camicia bianca pulita', 'Light blue oxford, open': 'Oxford azzurro, aperta', 'Navy polo, clean bg': 'Polo blu, sfondo pulito', 'Chambray, white bg': 'Chambray, sfondo bianco', 'Plaid button-up, neutral': 'Camicia a quadri, neutra', 'Plain white tee, casual': 'T-shirt bianca semplice, casual', 'Plain black tee, casual': 'T-shirt nera semplice, casual', 'Henley, warm window light': 'Henley, calda luce di finestra',
  'Warm tones, sunset light': 'Toni caldi, luce del tramonto', 'Green park, daylight': 'Parco verde, luce del giorno', 'City skyline, rooftop': 'Skyline, terrazza', 'Walking, urban street': 'Camminando, strada urbana',
  'White linen, sunglasses, beach': 'Lino bianco, occhiali da sole, spiaggia', 'Winter jacket, snowy peaks': 'Giacca invernale, cime innevate', 'Luxury pool, sunny vacation': 'Piscina di lusso, vacanza soleggiata', 'Sweater, golden fall foliage': 'Maglione, foglie d’autunno dorate', 'Outdoor jacket, scenic lake': 'Giacca outdoor, lago panoramico',
  'Black leather, urban': 'Pelle nera, urban', 'All black, dramatic': 'Tutto nero, drammatico', 'Red/emerald blazer': 'Blazer rosso/smeraldo', 'Leather jacket, motorbike': 'Giacca di pelle, moto', 'Smart casual, classic car': 'Smart casual, auto d’epoca',
  'Arms crossed, dark suit': 'Braccia incrociate, completo scuro', 'Seated at desk, engaging': 'Seduto alla scrivania, coinvolgente', 'Leaning casual, outdoor': 'Appoggiato casual, esterno', 'Leaning, modern office': 'Appoggiato, ufficio moderno', 'Relaxed, urban background': 'Rilassato, sfondo urbano', 'Hand near chin, intellectual': 'Mano vicino al mento, intellettuale', 'Tablet, modern office': 'Tablet, ufficio moderno',
  'Navy blazer, white blouse': 'Blazer blu, camicetta bianca', 'Charcoal suit, modern': 'Tailleur antracite, moderno', 'Black blazer, powerful': 'Blazer nero, deciso', 'Pinstripe blazer, silk': 'Blazer gessato, seta', 'Black sheath, refined': 'Tubino nero, raffinato', 'Silk blouse, tweed': 'Camicetta di seta, tweed',
  'Cream blazer + tee': 'Blazer crema + t-shirt', 'Black turtleneck + gray': 'Dolcevita nero + grigio', 'Navy silk, modern office': 'Seta blu, ufficio moderno', 'Beige cardigan, warm': 'Cardigan beige, caldo', 'Matching knit, neutral': 'Maglia coordinata, neutra', 'Light blue shirt, modern': 'Camicia azzurra, moderna',
  'Silk blouse, candlelit': 'Camicetta di seta, a lume di candela', 'Cocktail dress, evening': 'Abito da cocktail, sera', 'Rooftop bar, city lights': 'Rooftop bar, luci della città', 'Intimate, candlelight': 'Intimo, lume di candela', 'Smart casual, bistro': 'Smart casual, bistrò',
  'Red suit, statement': 'Tailleur rosso, statement', 'Green blazer, bold': 'Blazer verde, audace', 'Deep burgundy silk, bold': 'Seta bordeaux intenso, audace', 'Cobalt blue, statement': 'Blu cobalto, statement', 'Deep purple, expressive': 'Viola intenso, espressivo',
  'White tee, green outdoor': 'T-shirt bianca, verde esterno', 'Soft knit, window light': 'Maglia morbida, luce di finestra', 'Chambray, fresh white bg': 'Chambray, sfondo bianco fresco', 'Casual sweater, café': 'Maglione casual, caffè', 'Light blouse, park bg': 'Camicetta leggera, parco',
  'City panorama, golden hour': 'Panorama urbano, golden hour', 'Modern architecture bg': 'Architettura moderna',
  'Linen blouse, coastal': 'Camicetta di lino, costa', 'With a horse, countryside': 'Con un cavallo, campagna',
  'Arms crossed, blazer': 'Braccia incrociate, blazer', 'Relaxed pose, urban': 'Posa rilassata, urban', 'Hand near chin, elegant': 'Mano vicino al mento, elegante',
  'Black leather, edgy': 'Pelle nera, grintoso', 'Black evening top, lights': 'Top da sera nero, luci', 'Elegant gown, black-tie gala': 'Abito elegante, gala black-tie',
}

const pt: Record<string, string> = {
  'Formal / Corporate Power': 'Formal / Corporativo', 'Smart Casual / Business Modern': 'Smart Casual / Business moderno', 'Restaurant / Date Night': 'Restaurante / Encontro', 'Tech Founder / Sweater': 'Tech Founder / Suéter', 'Casual Professional': 'Casual profissional', 'Outdoor / Lifestyle': 'Ao ar livre / Lifestyle', 'Travel / Adventure': 'Viagem / Aventura', 'Creative / Bold': 'Criativo / Ousado', 'Specialty Poses': 'Poses especiais', 'Casual / Approachable': 'Casual / Acessível', 'Evening / Statement': 'Noite / Statement',
  'Navy suit, modern office': 'Terno azul-marinho, escritório moderno', 'Navy suit, city skyline': 'Terno azul-marinho, skyline', 'Black suit, dramatic dark bg': 'Terno preto, fundo escuro', 'Light grey suit, premium office': 'Terno cinza-claro, escritório premium', 'Pinstripe suit + tie': 'Terno risca de giz + gravata', 'Three piece suit + vest': 'Terno de três peças + colete', 'Black suit, dramatic light': 'Terno preto, luz dramática', 'Dark suit, red tie, skyscrapers': 'Terno escuro, gravata vermelha, arranha-céus',
  'Navy blazer, open collar': 'Blazer azul-marinho, gola aberta', 'Gray blazer, blue bg': 'Blazer cinza, fundo azul', 'Beige linen suit': 'Terno de linho bege', 'Teal blazer, white tee': 'Blazer azul-petróleo, camiseta branca', 'Light blue blazer, office': 'Blazer azul-claro, escritório', 'Black blazer + turtleneck': 'Blazer preto + gola alta', 'Light gray suit, no tie': 'Terno cinza-claro, sem gravata',
  'Upscale restaurant, candlelit': 'Restaurante sofisticado, à luz de velas', 'At wine bar, warm light': 'No wine bar, luz quente', 'Coffee shop, ambient': 'Cafeteria, atmosfera', 'City lights, evening': 'Luzes da cidade, noite',
  'Gray turtleneck, minimal': 'Gola alta cinza, minimalista', 'Crew neck over collar': 'Gola careca sobre camisa', 'Chunky knit, warm light': 'Tricô grosso, luz quente', 'Blue V-neck over collar': 'Gola V azul sobre camisa',
  'Clean white shirt': 'Camisa branca impecável', 'Light blue oxford, open': 'Oxford azul-claro, aberta', 'Navy polo, clean bg': 'Polo azul-marinho, fundo limpo', 'Chambray, white bg': 'Chambray, fundo branco', 'Plaid button-up, neutral': 'Camisa xadrez, neutra', 'Plain white tee, casual': 'Camiseta branca lisa, casual', 'Plain black tee, casual': 'Camiseta preta lisa, casual', 'Henley, warm window light': 'Henley, luz quente de janela',
  'Warm tones, sunset light': 'Tons quentes, luz do pôr do sol', 'Green park, daylight': 'Parque verde, luz do dia', 'City skyline, rooftop': 'Skyline, terraço', 'Walking, urban street': 'Caminhando, rua urbana',
  'White linen, sunglasses, beach': 'Linho branco, óculos de sol, praia', 'Winter jacket, snowy peaks': 'Casaco de inverno, picos nevados', 'Luxury pool, sunny vacation': 'Piscina de luxo, férias ensolaradas', 'Sweater, golden fall foliage': 'Suéter, folhagem dourada de outono', 'Outdoor jacket, scenic lake': 'Casaco outdoor, lago cênico',
  'Black leather, urban': 'Couro preto, urbano', 'All black, dramatic': 'Todo preto, dramático', 'Red/emerald blazer': 'Blazer vermelho/esmeralda', 'Leather jacket, motorbike': 'Jaqueta de couro, moto', 'Smart casual, classic car': 'Smart casual, carro clássico',
  'Arms crossed, dark suit': 'Braços cruzados, terno escuro', 'Seated at desk, engaging': 'Sentado à mesa, envolvente', 'Leaning casual, outdoor': 'Apoiado casual, ao ar livre', 'Leaning, modern office': 'Apoiado, escritório moderno', 'Relaxed, urban background': 'Relaxado, fundo urbano', 'Hand near chin, intellectual': 'Mão perto do queixo, intelectual', 'Tablet, modern office': 'Tablet, escritório moderno',
  'Navy blazer, white blouse': 'Blazer azul-marinho, blusa branca', 'Charcoal suit, modern': 'Tailleur grafite, moderno', 'Black blazer, powerful': 'Blazer preto, marcante', 'Pinstripe blazer, silk': 'Blazer risca de giz, seda', 'Black sheath, refined': 'Vestido tubinho preto, refinado', 'Silk blouse, tweed': 'Blusa de seda, tweed',
  'Cream blazer + tee': 'Blazer creme + camiseta', 'Black turtleneck + gray': 'Gola alta preta + cinza', 'Navy silk, modern office': 'Seda azul-marinho, escritório moderno', 'Beige cardigan, warm': 'Cardigã bege, aconchegante', 'Matching knit, neutral': 'Tricô combinando, neutro', 'Light blue shirt, modern': 'Camisa azul-clara, moderna',
  'Silk blouse, candlelit': 'Blusa de seda, à luz de velas', 'Cocktail dress, evening': 'Vestido de coquetel, noite', 'Rooftop bar, city lights': 'Bar no terraço, luzes da cidade', 'Intimate, candlelight': 'Intimista, luz de velas', 'Smart casual, bistro': 'Smart casual, bistrô',
  'Red suit, statement': 'Terno vermelho, statement', 'Green blazer, bold': 'Blazer verde, ousado', 'Deep burgundy silk, bold': 'Seda bordô profundo, ousado', 'Cobalt blue, statement': 'Azul cobalto, statement', 'Deep purple, expressive': 'Roxo profundo, expressivo',
  'White tee, green outdoor': 'Camiseta branca, verde ao ar livre', 'Soft knit, window light': 'Tricô macio, luz de janela', 'Chambray, fresh white bg': 'Chambray, fundo branco fresco', 'Casual sweater, café': 'Suéter casual, café', 'Light blouse, park bg': 'Blusa leve, parque',
  'City panorama, golden hour': 'Panorama urbano, golden hour', 'Modern architecture bg': 'Arquitetura moderna',
  'Linen blouse, coastal': 'Blusa de linho, litoral', 'With a horse, countryside': 'Com um cavalo, campo',
  'Arms crossed, blazer': 'Braços cruzados, blazer', 'Relaxed pose, urban': 'Pose relaxada, urbano', 'Hand near chin, elegant': 'Mão perto do queixo, elegante',
  'Black leather, edgy': 'Couro preto, ousado', 'Black evening top, lights': 'Top de noite preto, luzes', 'Elegant gown, black-tie gala': 'Vestido elegante, gala black-tie',
}

const MAPS: Record<Locale, Record<string, string>> = { en: {}, nl, fr, de, es, it, pt }

// Vertaal categorie-naam of stijl-beschrijving (Engelse brontekst als sleutel). Fallback = Engels.
export function tr(text: string, locale: Locale): string {
  if (locale === 'en') return text
  return MAPS[locale]?.[text] ?? text
}
