import type { Locale } from '@/lib/i18n'

// SEO-contentpagina's ("guides"). Elke guide is per taal vertaald.
export type GuideBlock =
  | { t: 'h2'; text: string }
  | { t: 'p'; text: string }
  | { t: 'ul'; items: string[] }
  | { t: 'ol'; items: string[] }

export interface GuideContent {
  metaTitle: string
  metaDescription: string
  h1: string
  intro: string
  blocks: GuideBlock[]
  ctaText: string
  ctaSub: string
}

// slug -> per taal. Voeg nieuwe guides toe door een nieuwe slug-key toe te voegen.
export const GUIDES: Record<string, Record<Locale, GuideContent>> = {
  'ai-headshots-for-linkedin': {
    en: {
      metaTitle: 'AI Headshots for LinkedIn — Professional Photo Without a Photographer',
      metaDescription: 'Get a professional LinkedIn photo without a photographer. Turn a few selfies into polished AI headshots for your LinkedIn profile in about 30 minutes.',
      h1: 'AI Headshots for LinkedIn',
      intro: 'Your LinkedIn photo is often the first impression recruiters, clients and colleagues get of you. A polished, professional headshot builds instant trust — but booking a photographer is expensive and slow. Nova Imago turns a few selfies into professional LinkedIn headshots with AI, in about 30 minutes.',
      blocks: [
        { t: 'h2', text: 'Why your LinkedIn photo matters' },
        { t: 'p', text: 'Profiles with a professional photo get far more views, connection requests and replies than those without. A clear, friendly, well-lit headshot signals that you take your professional presence seriously.' },
        { t: 'h2', text: 'How to get your LinkedIn headshot with AI' },
        { t: 'ol', items: [
          'Upload 8–15 clear selfies from different angles.',
          'We train a personal AI model of your face.',
          'Pick your favourite styles — corporate, smart-casual and more.',
          'Download your professional headshots in about 30 minutes.',
        ] },
        { t: 'h2', text: 'Tips for the best LinkedIn headshot' },
        { t: 'ul', items: [
          'Choose a style that matches your industry (formal for finance and law, smart-casual for tech and creative roles).',
          'Go for a clean, uncluttered background.',
          'A natural, approachable smile works best.',
          'Use a high-resolution image so it stays sharp on every device.',
        ] },
        { t: 'h2', text: 'AI headshots vs. a photographer' },
        { t: 'p', text: 'A studio shoot costs hundreds and takes days to arrange. AI headshots cost a fraction, are ready in minutes, and give you dozens of styles to choose from — with a money-back guarantee if you don’t get a usable shot.' },
      ],
      ctaText: 'Create my LinkedIn headshots',
      ctaSub: 'Ready in ~30 minutes · money-back guarantee',
    },
    nl: {
      metaTitle: 'AI-headshots voor LinkedIn — professionele foto zonder fotograaf',
      metaDescription: 'Een professionele LinkedIn-foto zonder fotograaf. Zet een paar selfies om in verzorgde AI-headshots voor je LinkedIn-profiel in ~30 minuten.',
      h1: 'AI-headshots voor LinkedIn',
      intro: 'Je LinkedIn-foto is vaak de eerste indruk die recruiters, klanten en collega’s van je krijgen. Een verzorgde, professionele headshot wekt meteen vertrouwen — maar een fotograaf boeken is duur en traag. Nova Imago zet een paar selfies om in professionele LinkedIn-headshots met AI, in ~30 minuten.',
      blocks: [
        { t: 'h2', text: 'Waarom je LinkedIn-foto ertoe doet' },
        { t: 'p', text: 'Profielen met een professionele foto krijgen veel meer weergaven, connectieverzoeken en reacties dan profielen zonder. Een scherpe, vriendelijke, goed belichte headshot toont dat je je professionele aanwezigheid serieus neemt.' },
        { t: 'h2', text: 'Zo krijg je je LinkedIn-headshot met AI' },
        { t: 'ol', items: [
          'Upload 8–15 scherpe selfies vanuit verschillende hoeken.',
          'Wij trainen een persoonlijk AI-model van je gezicht.',
          'Kies je favoriete stijlen — zakelijk, smart-casual en meer.',
          'Download je professionele headshots in ~30 minuten.',
        ] },
        { t: 'h2', text: 'Tips voor de beste LinkedIn-headshot' },
        { t: 'ul', items: [
          'Kies een stijl die past bij je sector (formeel voor finance en recht, smart-casual voor tech en creatieve functies).',
          'Ga voor een rustige, opgeruimde achtergrond.',
          'Een natuurlijke, toegankelijke glimlach werkt het best.',
          'Gebruik een afbeelding met hoge resolutie zodat ze op elk toestel scherp blijft.',
        ] },
        { t: 'h2', text: 'AI-headshots vs. een fotograaf' },
        { t: 'p', text: 'Een studioshoot kost honderden euro’s en duurt dagen om te regelen. AI-headshots kosten een fractie, zijn klaar in minuten en geven je tientallen stijlen om uit te kiezen — met geld-terug-garantie als je geen bruikbare foto krijgt.' },
      ],
      ctaText: 'Maak mijn LinkedIn-headshots',
      ctaSub: 'Klaar in ~30 minuten · geld-terug-garantie',
    },
    fr: {
      metaTitle: 'Portraits IA pour LinkedIn — photo professionnelle sans photographe',
      metaDescription: 'Une photo LinkedIn professionnelle sans photographe. Transformez quelques selfies en portraits IA soignés pour votre profil LinkedIn en ~30 minutes.',
      h1: 'Portraits IA pour LinkedIn',
      intro: 'Votre photo LinkedIn est souvent la première impression que recruteurs, clients et collègues ont de vous. Un portrait professionnel et soigné inspire confiance immédiatement — mais réserver un photographe coûte cher et prend du temps. Nova Imago transforme quelques selfies en portraits LinkedIn professionnels grâce à l’IA, en ~30 minutes.',
      blocks: [
        { t: 'h2', text: 'Pourquoi votre photo LinkedIn compte' },
        { t: 'p', text: 'Les profils avec une photo professionnelle obtiennent bien plus de vues, de demandes de connexion et de réponses. Un portrait net, avenant et bien éclairé montre que vous prenez votre présence professionnelle au sérieux.' },
        { t: 'h2', text: 'Comment obtenir votre portrait LinkedIn avec l’IA' },
        { t: 'ol', items: [
          'Envoyez 8 à 15 selfies nets sous différents angles.',
          'Nous entraînons un modèle IA personnel de votre visage.',
          'Choisissez vos styles préférés — corporate, smart-casual et plus.',
          'Téléchargez vos portraits professionnels en ~30 minutes.',
        ] },
        { t: 'h2', text: 'Conseils pour le meilleur portrait LinkedIn' },
        { t: 'ul', items: [
          'Choisissez un style adapté à votre secteur (formel pour la finance et le droit, smart-casual pour la tech et les métiers créatifs).',
          'Optez pour un arrière-plan sobre et épuré.',
          'Un sourire naturel et avenant fonctionne le mieux.',
          'Utilisez une image en haute résolution pour qu’elle reste nette sur tous les appareils.',
        ] },
        { t: 'h2', text: 'Portraits IA vs. un photographe' },
        { t: 'p', text: 'Une séance en studio coûte des centaines d’euros et prend des jours à organiser. Les portraits IA coûtent une fraction, sont prêts en minutes et offrent des dizaines de styles — avec une garantie satisfait ou remboursé si vous n’obtenez pas de photo utilisable.' },
      ],
      ctaText: 'Créer mes portraits LinkedIn',
      ctaSub: 'Prêts en ~30 minutes · satisfait ou remboursé',
    },
    de: {
      metaTitle: 'KI-Headshots für LinkedIn — professionelles Foto ohne Fotograf',
      metaDescription: 'Ein professionelles LinkedIn-Foto ohne Fotograf. Verwandle ein paar Selfies in gepflegte KI-Headshots für dein LinkedIn-Profil in ~30 Minuten.',
      h1: 'KI-Headshots für LinkedIn',
      intro: 'Dein LinkedIn-Foto ist oft der erste Eindruck, den Recruiter, Kunden und Kolleg:innen von dir bekommen. Ein gepflegter, professioneller Headshot schafft sofort Vertrauen — aber einen Fotografen zu buchen ist teuer und langsam. Nova Imago verwandelt ein paar Selfies mit KI in professionelle LinkedIn-Headshots, in ~30 Minuten.',
      blocks: [
        { t: 'h2', text: 'Warum dein LinkedIn-Foto zählt' },
        { t: 'p', text: 'Profile mit einem professionellen Foto erhalten deutlich mehr Aufrufe, Kontaktanfragen und Antworten als solche ohne. Ein klarer, sympathischer, gut ausgeleuchteter Headshot zeigt, dass du deinen professionellen Auftritt ernst nimmst.' },
        { t: 'h2', text: 'So bekommst du deinen LinkedIn-Headshot mit KI' },
        { t: 'ol', items: [
          'Lade 8–15 scharfe Selfies aus verschiedenen Winkeln hoch.',
          'Wir trainieren ein persönliches KI-Modell deines Gesichts.',
          'Wähle deine Lieblingsstile — Business, Smart Casual und mehr.',
          'Lade deine professionellen Headshots in ~30 Minuten herunter.',
        ] },
        { t: 'h2', text: 'Tipps für den besten LinkedIn-Headshot' },
        { t: 'ul', items: [
          'Wähle einen Stil, der zu deiner Branche passt (formell für Finanzen und Recht, Smart Casual für Tech und kreative Rollen).',
          'Setze auf einen ruhigen, aufgeräumten Hintergrund.',
          'Ein natürliches, sympathisches Lächeln wirkt am besten.',
          'Nutze ein hochauflösendes Bild, damit es auf jedem Gerät scharf bleibt.',
        ] },
        { t: 'h2', text: 'KI-Headshots vs. ein Fotograf' },
        { t: 'p', text: 'Ein Studioshooting kostet Hunderte und braucht Tage Vorbereitung. KI-Headshots kosten einen Bruchteil, sind in Minuten fertig und bieten Dutzende Stile zur Auswahl — mit Geld-zurück-Garantie, falls du kein brauchbares Foto bekommst.' },
      ],
      ctaText: 'Meine LinkedIn-Headshots erstellen',
      ctaSub: 'Fertig in ~30 Minuten · Geld-zurück-Garantie',
    },
    es: {
      metaTitle: 'Retratos con IA para LinkedIn — foto profesional sin fotógrafo',
      metaDescription: 'Una foto profesional de LinkedIn sin fotógrafo. Convierte unos selfies en retratos con IA pulidos para tu perfil de LinkedIn en ~30 minutos.',
      h1: 'Retratos con IA para LinkedIn',
      intro: 'Tu foto de LinkedIn suele ser la primera impresión que reclutadores, clientes y colegas tienen de ti. Un retrato profesional y cuidado genera confianza al instante — pero contratar a un fotógrafo es caro y lento. Nova Imago convierte unos selfies en retratos profesionales para LinkedIn con IA, en ~30 minutos.',
      blocks: [
        { t: 'h2', text: 'Por qué importa tu foto de LinkedIn' },
        { t: 'p', text: 'Los perfiles con una foto profesional reciben muchas más visitas, solicitudes de conexión y respuestas que los que no la tienen. Un retrato nítido, cercano y bien iluminado demuestra que te tomas en serio tu presencia profesional.' },
        { t: 'h2', text: 'Cómo conseguir tu retrato de LinkedIn con IA' },
        { t: 'ol', items: [
          'Sube 8–15 selfies nítidos desde distintos ángulos.',
          'Entrenamos un modelo de IA personal de tu rostro.',
          'Elige tus estilos favoritos — corporativo, smart-casual y más.',
          'Descarga tus retratos profesionales en ~30 minutos.',
        ] },
        { t: 'h2', text: 'Consejos para el mejor retrato de LinkedIn' },
        { t: 'ul', items: [
          'Elige un estilo acorde a tu sector (formal para finanzas y derecho, smart-casual para tecnología y perfiles creativos).',
          'Opta por un fondo limpio y despejado.',
          'Una sonrisa natural y cercana funciona mejor.',
          'Usa una imagen de alta resolución para que se vea nítida en todos los dispositivos.',
        ] },
        { t: 'h2', text: 'Retratos con IA vs. un fotógrafo' },
        { t: 'p', text: 'Una sesión de estudio cuesta cientos y tarda días en organizarse. Los retratos con IA cuestan una fracción, están listos en minutos y ofrecen decenas de estilos — con garantía de devolución si no obtienes una foto utilizable.' },
      ],
      ctaText: 'Crear mis retratos de LinkedIn',
      ctaSub: 'Listos en ~30 minutos · garantía de devolución',
    },
    it: {
      metaTitle: 'Ritratti IA per LinkedIn — foto professionale senza fotografo',
      metaDescription: 'Una foto LinkedIn professionale senza fotografo. Trasforma qualche selfie in ritratti IA curati per il tuo profilo LinkedIn in ~30 minuti.',
      h1: 'Ritratti IA per LinkedIn',
      intro: 'La tua foto LinkedIn è spesso la prima impressione che recruiter, clienti e colleghi hanno di te. Un ritratto professionale e curato ispira fiducia immediata — ma prenotare un fotografo è costoso e lento. Nova Imago trasforma qualche selfie in ritratti LinkedIn professionali con l’IA, in ~30 minuti.',
      blocks: [
        { t: 'h2', text: 'Perché la tua foto LinkedIn conta' },
        { t: 'p', text: 'I profili con una foto professionale ottengono molte più visualizzazioni, richieste di collegamento e risposte di quelli senza. Un ritratto nitido, cordiale e ben illuminato mostra che prendi sul serio la tua presenza professionale.' },
        { t: 'h2', text: 'Come ottenere il tuo ritratto LinkedIn con l’IA' },
        { t: 'ol', items: [
          'Carica 8–15 selfie nitidi da angolazioni diverse.',
          'Alleniamo un modello IA personale del tuo volto.',
          'Scegli i tuoi stili preferiti — corporate, smart-casual e altro.',
          'Scarica i tuoi ritratti professionali in ~30 minuti.',
        ] },
        { t: 'h2', text: 'Consigli per il miglior ritratto LinkedIn' },
        { t: 'ul', items: [
          'Scegli uno stile adatto al tuo settore (formale per finanza e diritto, smart-casual per tech e ruoli creativi).',
          'Punta su uno sfondo pulito e ordinato.',
          'Un sorriso naturale e cordiale funziona meglio.',
          'Usa un’immagine ad alta risoluzione così resta nitida su ogni dispositivo.',
        ] },
        { t: 'h2', text: 'Ritratti IA vs. un fotografo' },
        { t: 'p', text: 'Un servizio in studio costa centinaia di euro e richiede giorni di organizzazione. I ritratti IA costano una frazione, sono pronti in minuti e offrono decine di stili — con garanzia soddisfatti o rimborsati se non ottieni una foto utilizzabile.' },
      ],
      ctaText: 'Crea i miei ritratti LinkedIn',
      ctaSub: 'Pronti in ~30 minuti · soddisfatti o rimborsati',
    },
    pt: {
      metaTitle: 'Retratos com IA para LinkedIn — foto profissional sem fotógrafo',
      metaDescription: 'Uma foto de LinkedIn profissional sem fotógrafo. Transforme algumas selfies em retratos com IA cuidados para o seu perfil de LinkedIn em ~30 minutos.',
      h1: 'Retratos com IA para LinkedIn',
      intro: 'A sua foto de LinkedIn é muitas vezes a primeira impressão que recrutadores, clientes e colegas têm de si. Um retrato profissional e cuidado gera confiança imediata — mas contratar um fotógrafo é caro e demorado. A Nova Imago transforma algumas selfies em retratos profissionais para LinkedIn com IA, em ~30 minutos.',
      blocks: [
        { t: 'h2', text: 'Porque a sua foto de LinkedIn importa' },
        { t: 'p', text: 'Os perfis com uma foto profissional recebem muito mais visualizações, pedidos de ligação e respostas do que os que não têm. Um retrato nítido, simpático e bem iluminado mostra que leva a sua presença profissional a sério.' },
        { t: 'h2', text: 'Como obter o seu retrato de LinkedIn com IA' },
        { t: 'ol', items: [
          'Carregue 8–15 selfies nítidas de ângulos diferentes.',
          'Treinamos um modelo de IA pessoal do seu rosto.',
          'Escolha os seus estilos favoritos — corporativo, smart-casual e mais.',
          'Descarregue os seus retratos profissionais em ~30 minutos.',
        ] },
        { t: 'h2', text: 'Dicas para o melhor retrato de LinkedIn' },
        { t: 'ul', items: [
          'Escolha um estilo adequado ao seu setor (formal para finanças e direito, smart-casual para tecnologia e funções criativas).',
          'Opte por um fundo limpo e sem distrações.',
          'Um sorriso natural e simpático funciona melhor.',
          'Use uma imagem de alta resolução para que fique nítida em todos os dispositivos.',
        ] },
        { t: 'h2', text: 'Retratos com IA vs. um fotógrafo' },
        { t: 'p', text: 'Uma sessão em estúdio custa centenas e demora dias a organizar. Os retratos com IA custam uma fração, ficam prontos em minutos e oferecem dezenas de estilos — com garantia de reembolso se não obtiver uma foto utilizável.' },
      ],
      ctaText: 'Criar os meus retratos de LinkedIn',
      ctaSub: 'Prontos em ~30 minutos · garantia de reembolso',
    },
  },

  'ai-headshots-vs-photographer': {
    en: {
      metaTitle: 'AI Headshots vs. a Photographer — Cost, Time & Quality Compared',
      metaDescription: 'AI headshots or a photographer? Compare cost, speed, variety and quality — and see when each option makes sense for your professional photo.',
      h1: 'AI Headshots vs. a Photographer',
      intro: 'Thinking about a professional headshot but not sure whether to book a photographer or use AI? Here’s an honest comparison of cost, time, variety and quality to help you decide.',
      blocks: [
        { t: 'h2', text: 'Cost' },
        { t: 'p', text: 'A professional photo shoot typically costs €150–400 for a single session. AI headshots cost a small fraction of that and include dozens of images, so you pay far less per usable photo.' },
        { t: 'h2', text: 'Time and convenience' },
        { t: 'p', text: 'A shoot means scheduling, travelling and often waiting days for edited photos. With AI you upload a few selfies from home and get your headshots in about 30 minutes.' },
        { t: 'h2', text: 'Variety of styles' },
        { t: 'p', text: 'A studio session usually gives you one look and a handful of usable shots. AI gives you dozens of styles and backgrounds — formal, smart-casual, outdoor and more — from a single upload.' },
        { t: 'h2', text: 'When a photographer still wins' },
        { t: 'p', text: 'A skilled photographer is unbeatable for very specific creative direction, full-body or group shots, or when you want a physical, in-person experience. For a polished profile photo, though, AI is faster and far cheaper.' },
        { t: 'h2', text: 'The verdict' },
        { t: 'p', text: 'For most people who just need a great professional headshot for LinkedIn, a CV or social profiles, AI delivers comparable quality in minutes, at a fraction of the price — with a money-back guarantee.' },
      ],
      ctaText: 'Try AI headshots', ctaSub: 'Ready in ~30 minutes · money-back guarantee',
    },
    nl: {
      metaTitle: 'AI-headshots vs. een fotograaf — kost, tijd & kwaliteit vergeleken',
      metaDescription: 'AI-headshots of een fotograaf? Vergelijk kost, snelheid, variatie en kwaliteit — en ontdek wanneer elke optie zinvol is voor je professionele foto.',
      h1: 'AI-headshots vs. een fotograaf',
      intro: 'Denk je aan een professionele headshot maar twijfel je tussen een fotograaf of AI? Hier is een eerlijke vergelijking van kost, tijd, variatie en kwaliteit om je te helpen kiezen.',
      blocks: [
        { t: 'h2', text: 'Kostprijs' },
        { t: 'p', text: 'Een professionele fotoshoot kost doorgaans €150–400 voor één sessie. AI-headshots kosten daar een fractie van en bevatten tientallen beelden, dus je betaalt veel minder per bruikbare foto.' },
        { t: 'h2', text: 'Tijd en gemak' },
        { t: 'p', text: 'Een shoot betekent plannen, verplaatsen en vaak dagen wachten op bewerkte foto’s. Met AI upload je een paar selfies van thuis en krijg je je headshots in ~30 minuten.' },
        { t: 'h2', text: 'Variatie aan stijlen' },
        { t: 'p', text: 'Een studiosessie geeft je meestal één look en een handvol bruikbare foto’s. AI geeft je tientallen stijlen en achtergronden — formeel, smart-casual, outdoor en meer — uit één upload.' },
        { t: 'h2', text: 'Wanneer een fotograaf toch wint' },
        { t: 'p', text: 'Een goede fotograaf is onklopbaar voor heel specifieke creatieve regie, volledige lichaams- of groepsfoto’s, of wanneer je een fysieke ervaring wil. Voor een verzorgde profielfoto is AI echter sneller en veel goedkoper.' },
        { t: 'h2', text: 'De conclusie' },
        { t: 'p', text: 'Voor de meeste mensen die gewoon een sterke professionele headshot nodig hebben voor LinkedIn, een cv of socials, levert AI vergelijkbare kwaliteit in minuten, voor een fractie van de prijs — met geld-terug-garantie.' },
      ],
      ctaText: 'Probeer AI-headshots', ctaSub: 'Klaar in ~30 minuten · geld-terug-garantie',
    },
    fr: {
      metaTitle: 'Portraits IA vs. un photographe — coût, temps et qualité comparés',
      metaDescription: 'Portraits IA ou photographe ? Comparez le coût, la rapidité, la variété et la qualité — et voyez quand chaque option a du sens pour votre photo pro.',
      h1: 'Portraits IA vs. un photographe',
      intro: 'Vous songez à un portrait professionnel mais hésitez entre un photographe et l’IA ? Voici une comparaison honnête du coût, du temps, de la variété et de la qualité pour vous aider à choisir.',
      blocks: [
        { t: 'h2', text: 'Coût' },
        { t: 'p', text: 'Une séance photo professionnelle coûte généralement 150 à 400 € pour une session. Les portraits IA en coûtent une fraction et incluent des dizaines d’images : vous payez bien moins par photo utilisable.' },
        { t: 'h2', text: 'Temps et commodité' },
        { t: 'p', text: 'Une séance implique de planifier, se déplacer et souvent attendre des jours les photos retouchées. Avec l’IA, vous envoyez quelques selfies depuis chez vous et obtenez vos portraits en ~30 minutes.' },
        { t: 'h2', text: 'Variété de styles' },
        { t: 'p', text: 'Une séance en studio donne généralement un seul look et quelques photos utilisables. L’IA offre des dizaines de styles et d’arrière-plans — formel, smart-casual, extérieur et plus — à partir d’un seul envoi.' },
        { t: 'h2', text: 'Quand le photographe garde l’avantage' },
        { t: 'p', text: 'Un bon photographe est imbattable pour une direction créative très précise, des photos en pied ou de groupe, ou pour une expérience physique en personne. Mais pour une photo de profil soignée, l’IA est plus rapide et bien moins chère.' },
        { t: 'h2', text: 'Le verdict' },
        { t: 'p', text: 'Pour la plupart des gens qui veulent simplement un beau portrait professionnel pour LinkedIn, un CV ou les réseaux, l’IA offre une qualité comparable en quelques minutes, pour une fraction du prix — avec une garantie satisfait ou remboursé.' },
      ],
      ctaText: 'Essayer les portraits IA', ctaSub: 'Prêts en ~30 minutes · satisfait ou remboursé',
    },
    de: {
      metaTitle: 'KI-Headshots vs. ein Fotograf — Kosten, Zeit & Qualität im Vergleich',
      metaDescription: 'KI-Headshots oder ein Fotograf? Vergleiche Kosten, Tempo, Vielfalt und Qualität — und sieh, wann welche Option für dein professionelles Foto sinnvoll ist.',
      h1: 'KI-Headshots vs. ein Fotograf',
      intro: 'Du überlegst, ein professionelles Foto zu machen, bist dir aber unsicher zwischen Fotograf und KI? Hier ist ein ehrlicher Vergleich von Kosten, Zeit, Vielfalt und Qualität, der dir bei der Entscheidung hilft.',
      blocks: [
        { t: 'h2', text: 'Kosten' },
        { t: 'p', text: 'Ein professionelles Fotoshooting kostet meist 150–400 € pro Sitzung. KI-Headshots kosten nur einen Bruchteil davon und enthalten Dutzende Bilder — du zahlst also viel weniger pro brauchbarem Foto.' },
        { t: 'h2', text: 'Zeit und Komfort' },
        { t: 'p', text: 'Ein Shooting bedeutet Terminplanung, Anfahrt und oft tagelanges Warten auf bearbeitete Fotos. Mit KI lädst du von zu Hause ein paar Selfies hoch und erhältst deine Headshots in ~30 Minuten.' },
        { t: 'h2', text: 'Vielfalt an Stilen' },
        { t: 'p', text: 'Eine Studiositzung liefert meist einen Look und eine Handvoll brauchbarer Fotos. KI bietet Dutzende Stile und Hintergründe — formell, Smart Casual, Outdoor und mehr — aus einem einzigen Upload.' },
        { t: 'h2', text: 'Wann ein Fotograf trotzdem gewinnt' },
        { t: 'p', text: 'Ein guter Fotograf ist unschlagbar für sehr spezifische kreative Regie, Ganzkörper- oder Gruppenaufnahmen oder wenn du ein persönliches Erlebnis vor Ort willst. Für ein gepflegtes Profilfoto ist KI jedoch schneller und deutlich günstiger.' },
        { t: 'h2', text: 'Das Fazit' },
        { t: 'p', text: 'Für die meisten, die einfach einen tollen professionellen Headshot für LinkedIn, Lebenslauf oder Social Media brauchen, liefert KI vergleichbare Qualität in Minuten, zu einem Bruchteil des Preises — mit Geld-zurück-Garantie.' },
      ],
      ctaText: 'KI-Headshots ausprobieren', ctaSub: 'Fertig in ~30 Minuten · Geld-zurück-Garantie',
    },
    es: {
      metaTitle: 'Retratos con IA vs. un fotógrafo — coste, tiempo y calidad comparados',
      metaDescription: '¿Retratos con IA o un fotógrafo? Compara coste, rapidez, variedad y calidad — y descubre cuándo tiene sentido cada opción para tu foto profesional.',
      h1: 'Retratos con IA vs. un fotógrafo',
      intro: '¿Piensas en un retrato profesional pero dudas entre contratar a un fotógrafo o usar IA? Aquí tienes una comparación honesta de coste, tiempo, variedad y calidad para ayudarte a decidir.',
      blocks: [
        { t: 'h2', text: 'Coste' },
        { t: 'p', text: 'Una sesión de fotos profesional suele costar 150–400 € por sesión. Los retratos con IA cuestan una fracción e incluyen decenas de imágenes, así que pagas mucho menos por foto utilizable.' },
        { t: 'h2', text: 'Tiempo y comodidad' },
        { t: 'p', text: 'Una sesión implica agendar, desplazarse y a menudo esperar días por las fotos editadas. Con IA subes unos selfies desde casa y obtienes tus retratos en ~30 minutos.' },
        { t: 'h2', text: 'Variedad de estilos' },
        { t: 'p', text: 'Una sesión de estudio suele darte un solo look y un puñado de fotos utilizables. La IA te ofrece decenas de estilos y fondos — formal, smart-casual, exterior y más — desde una sola subida.' },
        { t: 'h2', text: 'Cuándo gana el fotógrafo' },
        { t: 'p', text: 'Un buen fotógrafo es imbatible para una dirección creativa muy específica, fotos de cuerpo entero o de grupo, o cuando quieres una experiencia presencial. Pero para una foto de perfil cuidada, la IA es más rápida y mucho más barata.' },
        { t: 'h2', text: 'El veredicto' },
        { t: 'p', text: 'Para la mayoría que solo necesita un buen retrato profesional para LinkedIn, un CV o redes, la IA ofrece una calidad comparable en minutos, por una fracción del precio — con garantía de devolución.' },
      ],
      ctaText: 'Probar retratos con IA', ctaSub: 'Listos en ~30 minutos · garantía de devolución',
    },
    it: {
      metaTitle: 'Ritratti IA vs. un fotografo — costo, tempo e qualità a confronto',
      metaDescription: 'Ritratti IA o un fotografo? Confronta costo, velocità, varietà e qualità — e scopri quando ha senso ciascuna opzione per la tua foto professionale.',
      h1: 'Ritratti IA vs. un fotografo',
      intro: 'Stai pensando a un ritratto professionale ma sei indeciso tra un fotografo e l’IA? Ecco un confronto onesto di costo, tempo, varietà e qualità per aiutarti a decidere.',
      blocks: [
        { t: 'h2', text: 'Costo' },
        { t: 'p', text: 'Un servizio fotografico professionale costa in genere 150–400 € a sessione. I ritratti IA costano una frazione e includono decine di immagini, quindi paghi molto meno per foto utilizzabile.' },
        { t: 'h2', text: 'Tempo e comodità' },
        { t: 'p', text: 'Un servizio richiede di prenotare, spostarsi e spesso attendere giorni per le foto ritoccate. Con l’IA carichi qualche selfie da casa e ottieni i ritratti in ~30 minuti.' },
        { t: 'h2', text: 'Varietà di stili' },
        { t: 'p', text: 'Una sessione in studio di solito offre un solo look e poche foto utilizzabili. L’IA offre decine di stili e sfondi — formale, smart-casual, outdoor e altro — da un solo caricamento.' },
        { t: 'h2', text: 'Quando vince ancora il fotografo' },
        { t: 'p', text: 'Un bravo fotografo è imbattibile per una direzione creativa molto specifica, foto a figura intera o di gruppo, o quando vuoi un’esperienza dal vivo. Ma per una foto profilo curata, l’IA è più veloce e molto più economica.' },
        { t: 'h2', text: 'Il verdetto' },
        { t: 'p', text: 'Per la maggior parte di chi vuole semplicemente un bel ritratto professionale per LinkedIn, un CV o i social, l’IA offre una qualità comparabile in minuti, a una frazione del prezzo — con garanzia soddisfatti o rimborsati.' },
      ],
      ctaText: 'Prova i ritratti IA', ctaSub: 'Pronti in ~30 minuti · soddisfatti o rimborsati',
    },
    pt: {
      metaTitle: 'Retratos com IA vs. um fotógrafo — custo, tempo e qualidade comparados',
      metaDescription: 'Retratos com IA ou um fotógrafo? Compare custo, rapidez, variedade e qualidade — e veja quando cada opção faz sentido para a sua foto profissional.',
      h1: 'Retratos com IA vs. um fotógrafo',
      intro: 'Está a pensar num retrato profissional mas em dúvida entre um fotógrafo e a IA? Aqui está uma comparação honesta de custo, tempo, variedade e qualidade para o ajudar a decidir.',
      blocks: [
        { t: 'h2', text: 'Custo' },
        { t: 'p', text: 'Uma sessão fotográfica profissional custa normalmente 150–400 € por sessão. Os retratos com IA custam uma fração e incluem dezenas de imagens, por isso paga muito menos por foto utilizável.' },
        { t: 'h2', text: 'Tempo e comodidade' },
        { t: 'p', text: 'Uma sessão implica marcar, deslocar-se e muitas vezes esperar dias pelas fotos editadas. Com IA carrega algumas selfies de casa e obtém os retratos em ~30 minutos.' },
        { t: 'h2', text: 'Variedade de estilos' },
        { t: 'p', text: 'Uma sessão de estúdio dá normalmente um só visual e um punhado de fotos utilizáveis. A IA oferece dezenas de estilos e fundos — formal, smart-casual, ao ar livre e mais — a partir de um único carregamento.' },
        { t: 'h2', text: 'Quando o fotógrafo ainda ganha' },
        { t: 'p', text: 'Um bom fotógrafo é imbatível para uma direção criativa muito específica, fotos de corpo inteiro ou de grupo, ou quando quer uma experiência presencial. Mas para uma foto de perfil cuidada, a IA é mais rápida e muito mais barata.' },
        { t: 'h2', text: 'O veredito' },
        { t: 'p', text: 'Para a maioria que só precisa de um bom retrato profissional para LinkedIn, um CV ou redes, a IA oferece qualidade comparável em minutos, por uma fração do preço — com garantia de reembolso.' },
      ],
      ctaText: 'Experimentar retratos com IA', ctaSub: 'Prontos em ~30 minutos · garantia de reembolso',
    },
  },

  'ai-headshots-for-cv': {
    en: {
      metaTitle: 'AI Headshots for Your CV / Resume — Look Professional in Minutes',
      metaDescription: 'Need a photo for your CV or resume? Turn a few selfies into a professional AI headshot in about 30 minutes — polished, consistent and ready to use.',
      h1: 'AI Headshots for Your CV',
      intro: 'A clear, professional photo can help your CV stand out and feel more personal. Nova Imago turns a few selfies into a polished headshot for your CV or resume in about 30 minutes — no photographer needed.',
      blocks: [
        { t: 'h2', text: 'Should your CV have a photo?' },
        { t: 'p', text: 'It depends on where you apply. In much of continental Europe a professional photo is common and expected, while in the US, UK and Ireland it’s usually left off. When a photo is expected, a clean, professional headshot makes a strong first impression.' },
        { t: 'h2', text: 'How to get your CV photo with AI' },
        { t: 'ol', items: ['Upload 8–15 clear selfies from different angles.', 'We train a personal AI model of your face.', 'Choose a formal or smart-casual style to match your field.', 'Download your CV photo in about 30 minutes.'] },
        { t: 'h2', text: 'Tips for a great CV photo' },
        { t: 'ul', items: ['Keep it head-and-shoulders with a neutral background.', 'Dress as you would for the role you want.', 'Choose a friendly, confident expression.', 'Use the same photo across your CV and LinkedIn for a consistent personal brand.'] },
        { t: 'h2', text: 'Why AI works well for CV photos' },
        { t: 'p', text: 'You get a consistent, professional result in minutes for a fraction of a studio price — and dozens of styles to match any industry, from finance to tech to creative.' },
      ],
      ctaText: 'Create my CV headshot', ctaSub: 'Ready in ~30 minutes · money-back guarantee',
    },
    nl: {
      metaTitle: 'AI-headshots voor je cv — professioneel ogen in minuten',
      metaDescription: 'Een foto nodig voor je cv? Zet een paar selfies om in een professionele AI-headshot in ~30 minuten — verzorgd, consistent en klaar voor gebruik.',
      h1: 'AI-headshots voor je cv',
      intro: 'Een scherpe, professionele foto laat je cv opvallen en voelt persoonlijker. Nova Imago zet een paar selfies om in een verzorgde headshot voor je cv in ~30 minuten — zonder fotograaf.',
      blocks: [
        { t: 'h2', text: 'Hoort er een foto op je cv?' },
        { t: 'p', text: 'Dat hangt af van waar je solliciteert. In een groot deel van continentaal Europa is een professionele foto gebruikelijk en verwacht, terwijl ze in de VS, het VK en Ierland meestal wordt weggelaten. Waar een foto verwacht wordt, maakt een verzorgde, professionele headshot een sterke eerste indruk.' },
        { t: 'h2', text: 'Zo krijg je je cv-foto met AI' },
        { t: 'ol', items: ['Upload 8–15 scherpe selfies vanuit verschillende hoeken.', 'Wij trainen een persoonlijk AI-model van je gezicht.', 'Kies een formele of smart-casual stijl die bij je vakgebied past.', 'Download je cv-foto in ~30 minuten.'] },
        { t: 'h2', text: 'Tips voor een sterke cv-foto' },
        { t: 'ul', items: ['Houd het bij hoofd-en-schouders met een neutrale achtergrond.', 'Kleed je zoals voor de functie die je wil.', 'Kies een vriendelijke, zelfverzekerde uitdrukking.', 'Gebruik dezelfde foto op je cv en LinkedIn voor een consistente persoonlijke branding.'] },
        { t: 'h2', text: 'Waarom AI goed werkt voor cv-foto’s' },
        { t: 'p', text: 'Je krijgt een consistent, professioneel resultaat in minuten voor een fractie van een studioprijs — en tientallen stijlen voor elke sector, van finance tot tech tot creatief.' },
      ],
      ctaText: 'Maak mijn cv-headshot', ctaSub: 'Klaar in ~30 minuten · geld-terug-garantie',
    },
    fr: {
      metaTitle: 'Portraits IA pour votre CV — un rendu professionnel en quelques minutes',
      metaDescription: 'Besoin d’une photo pour votre CV ? Transformez quelques selfies en portrait IA professionnel en ~30 minutes — soigné, cohérent et prêt à l’emploi.',
      h1: 'Portraits IA pour votre CV',
      intro: 'Une photo nette et professionnelle aide votre CV à se démarquer et le rend plus personnel. Nova Imago transforme quelques selfies en un portrait soigné pour votre CV en ~30 minutes — sans photographe.',
      blocks: [
        { t: 'h2', text: 'Faut-il une photo sur un CV ?' },
        { t: 'p', text: 'Cela dépend du pays. Dans une grande partie de l’Europe continentale, une photo professionnelle est courante et attendue, tandis qu’aux États-Unis, au Royaume-Uni et en Irlande on l’omet généralement. Quand une photo est attendue, un portrait soigné fait forte impression.' },
        { t: 'h2', text: 'Comment obtenir votre photo de CV avec l’IA' },
        { t: 'ol', items: ['Envoyez 8 à 15 selfies nets sous différents angles.', 'Nous entraînons un modèle IA personnel de votre visage.', 'Choisissez un style formel ou smart-casual adapté à votre domaine.', 'Téléchargez votre photo de CV en ~30 minutes.'] },
        { t: 'h2', text: 'Conseils pour une bonne photo de CV' },
        { t: 'ul', items: ['Restez en plan tête-épaules avec un arrière-plan neutre.', 'Habillez-vous comme pour le poste visé.', 'Adoptez une expression avenante et assurée.', 'Utilisez la même photo sur votre CV et LinkedIn pour une image cohérente.'] },
        { t: 'h2', text: 'Pourquoi l’IA convient aux photos de CV' },
        { t: 'p', text: 'Vous obtenez un résultat professionnel et cohérent en quelques minutes, pour une fraction du prix d’un studio — et des dizaines de styles pour tout secteur, de la finance à la tech en passant par le créatif.' },
      ],
      ctaText: 'Créer mon portrait de CV', ctaSub: 'Prêt en ~30 minutes · satisfait ou remboursé',
    },
    de: {
      metaTitle: 'KI-Headshots für deinen Lebenslauf — in Minuten professionell aussehen',
      metaDescription: 'Ein Foto für deinen Lebenslauf? Verwandle ein paar Selfies in ~30 Minuten in einen professionellen KI-Headshot — gepflegt, konsistent und einsatzbereit.',
      h1: 'KI-Headshots für deinen Lebenslauf',
      intro: 'Ein klares, professionelles Foto lässt deinen Lebenslauf hervorstechen und wirkt persönlicher. Nova Imago verwandelt ein paar Selfies in ~30 Minuten in einen gepflegten Headshot für deinen Lebenslauf — ohne Fotograf.',
      blocks: [
        { t: 'h2', text: 'Gehört ein Foto in den Lebenslauf?' },
        { t: 'p', text: 'Das hängt vom Land ab. In weiten Teilen Kontinentaleuropas ist ein professionelles Foto üblich und erwartet, während es in den USA, UK und Irland meist weggelassen wird. Wo ein Foto erwartet wird, hinterlässt ein gepflegter Headshot einen starken ersten Eindruck.' },
        { t: 'h2', text: 'So bekommst du dein Lebenslauf-Foto mit KI' },
        { t: 'ol', items: ['Lade 8–15 scharfe Selfies aus verschiedenen Winkeln hoch.', 'Wir trainieren ein persönliches KI-Modell deines Gesichts.', 'Wähle einen formellen oder Smart-Casual-Stil passend zu deiner Branche.', 'Lade dein Lebenslauf-Foto in ~30 Minuten herunter.'] },
        { t: 'h2', text: 'Tipps für ein starkes Lebenslauf-Foto' },
        { t: 'ul', items: ['Bleib bei Kopf-und-Schultern mit neutralem Hintergrund.', 'Kleide dich wie für die angestrebte Stelle.', 'Wähle einen freundlichen, selbstbewussten Ausdruck.', 'Nutze dasselbe Foto auf Lebenslauf und LinkedIn für ein einheitliches Bild.'] },
        { t: 'h2', text: 'Warum KI gut für Lebenslauf-Fotos ist' },
        { t: 'p', text: 'Du bekommst ein konsistentes, professionelles Ergebnis in Minuten zu einem Bruchteil des Studiopreises — und Dutzende Stile für jede Branche, von Finanzen über Tech bis Kreativ.' },
      ],
      ctaText: 'Meinen Lebenslauf-Headshot erstellen', ctaSub: 'Fertig in ~30 Minuten · Geld-zurück-Garantie',
    },
    es: {
      metaTitle: 'Retratos con IA para tu CV — luce profesional en minutos',
      metaDescription: '¿Necesitas una foto para tu CV? Convierte unos selfies en un retrato con IA profesional en ~30 minutos — pulido, consistente y listo para usar.',
      h1: 'Retratos con IA para tu CV',
      intro: 'Una foto nítida y profesional ayuda a que tu CV destaque y se sienta más personal. Nova Imago convierte unos selfies en un retrato cuidado para tu CV en ~30 minutos — sin fotógrafo.',
      blocks: [
        { t: 'h2', text: '¿Debe llevar foto tu CV?' },
        { t: 'p', text: 'Depende de dónde te postules. En buena parte de Europa continental una foto profesional es habitual y esperada, mientras que en EE. UU., Reino Unido e Irlanda suele omitirse. Cuando se espera una foto, un retrato cuidado causa una gran primera impresión.' },
        { t: 'h2', text: 'Cómo conseguir tu foto de CV con IA' },
        { t: 'ol', items: ['Sube 8–15 selfies nítidos desde distintos ángulos.', 'Entrenamos un modelo de IA personal de tu rostro.', 'Elige un estilo formal o smart-casual acorde a tu sector.', 'Descarga tu foto de CV en ~30 minutos.'] },
        { t: 'h2', text: 'Consejos para una buena foto de CV' },
        { t: 'ul', items: ['Manténla de cabeza y hombros con un fondo neutro.', 'Vístete como para el puesto que buscas.', 'Elige una expresión cercana y segura.', 'Usa la misma foto en tu CV y LinkedIn para una marca personal coherente.'] },
        { t: 'h2', text: 'Por qué la IA funciona para fotos de CV' },
        { t: 'p', text: 'Obtienes un resultado profesional y consistente en minutos por una fracción del precio de un estudio — y decenas de estilos para cualquier sector, de finanzas a tecnología o creativo.' },
      ],
      ctaText: 'Crear mi retrato de CV', ctaSub: 'Listo en ~30 minutos · garantía de devolución',
    },
    it: {
      metaTitle: 'Ritratti IA per il tuo CV — un aspetto professionale in pochi minuti',
      metaDescription: 'Ti serve una foto per il CV? Trasforma qualche selfie in un ritratto IA professionale in ~30 minuti — curato, coerente e pronto all’uso.',
      h1: 'Ritratti IA per il tuo CV',
      intro: 'Una foto nitida e professionale aiuta il tuo CV a distinguersi e lo rende più personale. Nova Imago trasforma qualche selfie in un ritratto curato per il tuo CV in ~30 minuti — senza fotografo.',
      blocks: [
        { t: 'h2', text: 'Il CV deve avere una foto?' },
        { t: 'p', text: 'Dipende da dove ti candidi. In gran parte dell’Europa continentale una foto professionale è comune e attesa, mentre negli USA, nel Regno Unito e in Irlanda di solito si omette. Dove la foto è attesa, un ritratto curato fa un’ottima prima impressione.' },
        { t: 'h2', text: 'Come ottenere la tua foto per il CV con l’IA' },
        { t: 'ol', items: ['Carica 8–15 selfie nitidi da angolazioni diverse.', 'Alleniamo un modello IA personale del tuo volto.', 'Scegli uno stile formale o smart-casual adatto al tuo settore.', 'Scarica la tua foto per il CV in ~30 minuti.'] },
        { t: 'h2', text: 'Consigli per una buona foto del CV' },
        { t: 'ul', items: ['Mantienila a testa e spalle con uno sfondo neutro.', 'Vestiti come per il ruolo che desideri.', 'Scegli un’espressione cordiale e sicura.', 'Usa la stessa foto su CV e LinkedIn per un’immagine coerente.'] },
        { t: 'h2', text: 'Perché l’IA funziona per le foto del CV' },
        { t: 'p', text: 'Ottieni un risultato professionale e coerente in minuti a una frazione del prezzo di uno studio — e decine di stili per ogni settore, dalla finanza al tech al creativo.' },
      ],
      ctaText: 'Crea il mio ritratto per il CV', ctaSub: 'Pronto in ~30 minuti · soddisfatti o rimborsati',
    },
    pt: {
      metaTitle: 'Retratos com IA para o seu CV — pareça profissional em minutos',
      metaDescription: 'Precisa de uma foto para o CV? Transforme algumas selfies num retrato com IA profissional em ~30 minutos — cuidado, coerente e pronto a usar.',
      h1: 'Retratos com IA para o seu CV',
      intro: 'Uma foto nítida e profissional ajuda o seu CV a destacar-se e torna-o mais pessoal. A Nova Imago transforma algumas selfies num retrato cuidado para o seu CV em ~30 minutos — sem fotógrafo.',
      blocks: [
        { t: 'h2', text: 'O CV deve ter foto?' },
        { t: 'p', text: 'Depende de onde se candidata. Em grande parte da Europa continental uma foto profissional é comum e esperada, enquanto nos EUA, Reino Unido e Irlanda costuma ser omitida. Quando a foto é esperada, um retrato cuidado causa uma forte primeira impressão.' },
        { t: 'h2', text: 'Como obter a foto do seu CV com IA' },
        { t: 'ol', items: ['Carregue 8–15 selfies nítidas de ângulos diferentes.', 'Treinamos um modelo de IA pessoal do seu rosto.', 'Escolha um estilo formal ou smart-casual adequado à sua área.', 'Descarregue a foto do seu CV em ~30 minutos.'] },
        { t: 'h2', text: 'Dicas para uma boa foto de CV' },
        { t: 'ul', items: ['Mantenha-a de cabeça e ombros com um fundo neutro.', 'Vista-se como para a função que pretende.', 'Escolha uma expressão simpática e confiante.', 'Use a mesma foto no CV e no LinkedIn para uma imagem coerente.'] },
        { t: 'h2', text: 'Porque a IA funciona para fotos de CV' },
        { t: 'p', text: 'Obtém um resultado profissional e coerente em minutos por uma fração do preço de um estúdio — e dezenas de estilos para qualquer setor, das finanças à tecnologia ao criativo.' },
      ],
      ctaText: 'Criar o retrato do meu CV', ctaSub: 'Pronto em ~30 minutos · garantia de reembolso',
    },
  },

  'ai-photos-for-dating': {
    en: {
      metaTitle: 'AI Photos for Your Dating Profile — Look Your Best, Still Look Like You',
      metaDescription: 'Get natural, attractive photos for your dating profile with AI. Turn a few selfies into a variety of authentic-looking shots in about 30 minutes.',
      h1: 'AI Photos for Your Dating Profile',
      intro: 'Your main dating photo decides whether people swipe right. A clear, natural, confident picture makes a huge difference — and Nova Imago turns a few selfies into a variety of attractive, authentic-looking photos in about 30 minutes.',
      blocks: [
        { t: 'h2', text: 'Why your main photo matters' },
        { t: 'p', text: 'On dating apps your first photo is everything — it’s the split-second decision to swipe or scroll. A sharp, well-lit, genuine shot with a warm expression consistently performs best.' },
        { t: 'h2', text: 'How to get dating photos with AI' },
        { t: 'ol', items: ['Upload 8–15 varied selfies with good lighting.', 'We train a personal AI model of your face.', 'Pick relaxed, natural styles — casual, outdoor, lifestyle.', 'Download a set of photos in about 30 minutes.'] },
        { t: 'h2', text: 'Tips for great dating photos' },
        { t: 'ul', items: ['Lead with a clear, smiling head-and-shoulders shot.', 'Mix in relaxed, casual and outdoor looks for variety.', 'Keep it authentic — the photos should still clearly look like you.', 'Avoid over-editing; natural and approachable beats overly polished.'] },
        { t: 'h2', text: 'Look your best — and still look like you' },
        { t: 'p', text: 'The goal is your best, most confident self, not a different person. Nova Imago is trained on your own selfies, so the results look like you on a great day — perfect for a genuine first impression.' },
      ],
      ctaText: 'Create my dating photos', ctaSub: 'Ready in ~30 minutes · money-back guarantee',
    },
    nl: {
      metaTitle: 'AI-foto’s voor je datingprofiel — op je best, en toch jezelf',
      metaDescription: 'Natuurlijke, aantrekkelijke foto’s voor je datingprofiel met AI. Zet een paar selfies om in een reeks authentiek ogende foto’s in ~30 minuten.',
      h1: 'AI-foto’s voor je datingprofiel',
      intro: 'Je hoofdfoto bepaalt of mensen naar rechts swipen. Een scherpe, natuurlijke, zelfverzekerde foto maakt een enorm verschil — en Nova Imago zet een paar selfies om in een reeks aantrekkelijke, authentiek ogende foto’s in ~30 minuten.',
      blocks: [
        { t: 'h2', text: 'Waarom je hoofdfoto ertoe doet' },
        { t: 'p', text: 'Op datingapps is je eerste foto alles — het is de splitsecondebeslissing om te swipen of door te scrollen. Een scherpe, goed belichte, oprechte foto met een warme uitdrukking presteert consequent het best.' },
        { t: 'h2', text: 'Zo krijg je datingfoto’s met AI' },
        { t: 'ol', items: ['Upload 8–15 gevarieerde selfies met goed licht.', 'Wij trainen een persoonlijk AI-model van je gezicht.', 'Kies ontspannen, natuurlijke stijlen — casual, outdoor, lifestyle.', 'Download een reeks foto’s in ~30 minuten.'] },
        { t: 'h2', text: 'Tips voor sterke datingfoto’s' },
        { t: 'ul', items: ['Begin met een scherpe, lachende hoofd-en-schouderfoto.', 'Mix ontspannen, casual en outdoor looks voor variatie.', 'Hou het authentiek — de foto’s moeten duidelijk op jou lijken.', 'Vermijd overbewerking; natuurlijk en toegankelijk wint van te gepolijst.'] },
        { t: 'h2', text: 'Op je best — en toch jezelf' },
        { t: 'p', text: 'Het doel is jouw beste, meest zelfverzekerde zelf, niet iemand anders. Nova Imago wordt getraind op je eigen selfies, dus de resultaten lijken op jou op een topdag — perfect voor een oprechte eerste indruk.' },
      ],
      ctaText: 'Maak mijn datingfoto’s', ctaSub: 'Klaar in ~30 minuten · geld-terug-garantie',
    },
    fr: {
      metaTitle: 'Photos IA pour votre profil de rencontre — au top, et toujours vous',
      metaDescription: 'Des photos naturelles et attirantes pour votre profil de rencontre grâce à l’IA. Transformez quelques selfies en une série de photos authentiques en ~30 minutes.',
      h1: 'Photos IA pour votre profil de rencontre',
      intro: 'Votre photo principale décide si l’on swipe à droite. Une image nette, naturelle et assurée fait une énorme différence — et Nova Imago transforme quelques selfies en une série de photos attirantes et authentiques en ~30 minutes.',
      blocks: [
        { t: 'h2', text: 'Pourquoi votre photo principale compte' },
        { t: 'p', text: 'Sur les applis de rencontre, votre première photo est tout — c’est la décision en une fraction de seconde de swiper ou de continuer. Une photo nette, bien éclairée et sincère avec une expression chaleureuse fonctionne toujours le mieux.' },
        { t: 'h2', text: 'Comment obtenir des photos de rencontre avec l’IA' },
        { t: 'ol', items: ['Envoyez 8 à 15 selfies variés bien éclairés.', 'Nous entraînons un modèle IA personnel de votre visage.', 'Choisissez des styles détendus et naturels — casual, extérieur, lifestyle.', 'Téléchargez une série de photos en ~30 minutes.'] },
        { t: 'h2', text: 'Conseils pour de belles photos de rencontre' },
        { t: 'ul', items: ['Commencez par une photo nette tête-épaules, souriante.', 'Variez avec des looks détendus, casual et en extérieur.', 'Restez authentique — les photos doivent clairement vous ressembler.', 'Évitez la sur-retouche ; naturel et avenant vaut mieux que trop lisse.'] },
        { t: 'h2', text: 'Au top — et toujours vous' },
        { t: 'p', text: 'L’objectif est votre meilleure version, la plus assurée, pas quelqu’un d’autre. Nova Imago s’entraîne sur vos propres selfies : les résultats vous ressemblent, un très bon jour — parfait pour une première impression sincère.' },
      ],
      ctaText: 'Créer mes photos de rencontre', ctaSub: 'Prêtes en ~30 minutes · satisfait ou remboursé',
    },
    de: {
      metaTitle: 'KI-Fotos für dein Dating-Profil — dein bestes Ich, trotzdem du',
      metaDescription: 'Natürliche, attraktive Fotos für dein Dating-Profil mit KI. Verwandle ein paar Selfies in ~30 Minuten in eine Auswahl authentisch wirkender Aufnahmen.',
      h1: 'KI-Fotos für dein Dating-Profil',
      intro: 'Dein Hauptfoto entscheidet, ob jemand nach rechts wischt. Ein klares, natürliches, selbstbewusstes Bild macht einen riesigen Unterschied — und Nova Imago verwandelt ein paar Selfies in ~30 Minuten in eine Auswahl attraktiver, authentisch wirkender Fotos.',
      blocks: [
        { t: 'h2', text: 'Warum dein Hauptfoto zählt' },
        { t: 'p', text: 'In Dating-Apps ist dein erstes Foto alles — es ist die Bruchteil-einer-Sekunde-Entscheidung, zu wischen oder weiterzuscrollen. Eine scharfe, gut ausgeleuchtete, echte Aufnahme mit warmer Ausstrahlung funktioniert durchweg am besten.' },
        { t: 'h2', text: 'So bekommst du Dating-Fotos mit KI' },
        { t: 'ol', items: ['Lade 8–15 abwechslungsreiche Selfies mit gutem Licht hoch.', 'Wir trainieren ein persönliches KI-Modell deines Gesichts.', 'Wähle entspannte, natürliche Stile — Casual, Outdoor, Lifestyle.', 'Lade eine Reihe von Fotos in ~30 Minuten herunter.'] },
        { t: 'h2', text: 'Tipps für tolle Dating-Fotos' },
        { t: 'ul', items: ['Beginne mit einer klaren, lächelnden Kopf-und-Schultern-Aufnahme.', 'Mische entspannte, lässige und Outdoor-Looks für Abwechslung.', 'Bleib authentisch — die Fotos sollten klar nach dir aussehen.', 'Vermeide Überbearbeitung; natürlich und sympathisch schlägt zu glatt.'] },
        { t: 'h2', text: 'Dein bestes Ich — und trotzdem du' },
        { t: 'p', text: 'Das Ziel ist dein bestes, selbstbewusstestes Ich, nicht eine andere Person. Nova Imago wird auf deinen eigenen Selfies trainiert, also sehen die Ergebnisse aus wie du an einem großartigen Tag — perfekt für einen echten ersten Eindruck.' },
      ],
      ctaText: 'Meine Dating-Fotos erstellen', ctaSub: 'Fertig in ~30 Minuten · Geld-zurück-Garantie',
    },
    es: {
      metaTitle: 'Fotos con IA para tu perfil de citas — luce genial, y sigue siendo tú',
      metaDescription: 'Consigue fotos naturales y atractivas para tu perfil de citas con IA. Convierte unos selfies en una variedad de fotos auténticas en ~30 minutos.',
      h1: 'Fotos con IA para tu perfil de citas',
      intro: 'Tu foto principal decide si te dan match. Una imagen nítida, natural y segura marca una gran diferencia — y Nova Imago convierte unos selfies en una variedad de fotos atractivas y de aspecto auténtico en ~30 minutos.',
      blocks: [
        { t: 'h2', text: 'Por qué importa tu foto principal' },
        { t: 'p', text: 'En las apps de citas tu primera foto lo es todo — es la decisión en una fracción de segundo de deslizar o seguir. Una foto nítida, bien iluminada y genuina, con una expresión cálida, funciona mejor de forma constante.' },
        { t: 'h2', text: 'Cómo conseguir fotos de citas con IA' },
        { t: 'ol', items: ['Sube 8–15 selfies variados con buena luz.', 'Entrenamos un modelo de IA personal de tu rostro.', 'Elige estilos relajados y naturales — casual, exterior, lifestyle.', 'Descarga un conjunto de fotos en ~30 minutos.'] },
        { t: 'h2', text: 'Consejos para buenas fotos de citas' },
        { t: 'ul', items: ['Empieza con una foto nítida de cabeza y hombros, sonriendo.', 'Combina looks relajados, casual y de exterior para dar variedad.', 'Mantén la autenticidad — las fotos deben parecerse claramente a ti.', 'Evita el exceso de edición; natural y cercano gana a demasiado pulido.'] },
        { t: 'h2', text: 'Luce genial — y sigue siendo tú' },
        { t: 'p', text: 'El objetivo es tu mejor versión, la más segura, no otra persona. Nova Imago se entrena con tus propios selfies, así que los resultados se parecen a ti en un gran día — perfecto para una primera impresión genuina.' },
      ],
      ctaText: 'Crear mis fotos de citas', ctaSub: 'Listas en ~30 minutos · garantía de devolución',
    },
    it: {
      metaTitle: 'Foto IA per il tuo profilo di incontri — al meglio, e sempre te',
      metaDescription: 'Foto naturali e attraenti per il tuo profilo di incontri con l’IA. Trasforma qualche selfie in una varietà di scatti dall’aspetto autentico in ~30 minuti.',
      h1: 'Foto IA per il tuo profilo di incontri',
      intro: 'La tua foto principale decide se ti danno un match. Un’immagine nitida, naturale e sicura fa un’enorme differenza — e Nova Imago trasforma qualche selfie in una varietà di foto attraenti e dall’aspetto autentico in ~30 minuti.',
      blocks: [
        { t: 'h2', text: 'Perché la tua foto principale conta' },
        { t: 'p', text: 'Nelle app di incontri la prima foto è tutto — è la decisione in una frazione di secondo se scorrere o passare. Uno scatto nitido, ben illuminato e genuino, con un’espressione calorosa, funziona sempre meglio.' },
        { t: 'h2', text: 'Come ottenere foto per gli incontri con l’IA' },
        { t: 'ol', items: ['Carica 8–15 selfie vari con buona luce.', 'Alleniamo un modello IA personale del tuo volto.', 'Scegli stili rilassati e naturali — casual, outdoor, lifestyle.', 'Scarica una serie di foto in ~30 minuti.'] },
        { t: 'h2', text: 'Consigli per ottime foto di incontri' },
        { t: 'ul', items: ['Inizia con uno scatto nitido a testa e spalle, sorridente.', 'Alterna look rilassati, casual e outdoor per varietà.', 'Resta autentico — le foto devono somigliarti chiaramente.', 'Evita l’eccesso di ritocco; naturale e cordiale batte troppo levigato.'] },
        { t: 'h2', text: 'Al meglio — e sempre te' },
        { t: 'p', text: 'L’obiettivo è la tua versione migliore e più sicura, non un’altra persona. Nova Imago si allena sui tuoi selfie, quindi i risultati ti somigliano in una giornata perfetta — ideale per una prima impressione genuina.' },
      ],
      ctaText: 'Crea le mie foto di incontri', ctaSub: 'Pronte in ~30 minuti · soddisfatti o rimborsati',
    },
    pt: {
      metaTitle: 'Fotos com IA para o seu perfil de encontros — no seu melhor, e ainda você',
      metaDescription: 'Fotos naturais e atraentes para o seu perfil de encontros com IA. Transforme algumas selfies numa variedade de fotos com aspeto autêntico em ~30 minutos.',
      h1: 'Fotos com IA para o seu perfil de encontros',
      intro: 'A sua foto principal decide se dão match. Uma imagem nítida, natural e confiante faz uma enorme diferença — e a Nova Imago transforma algumas selfies numa variedade de fotos atraentes e de aspeto autêntico em ~30 minutos.',
      blocks: [
        { t: 'h2', text: 'Porque a sua foto principal importa' },
        { t: 'p', text: 'Nas apps de encontros a primeira foto é tudo — é a decisão numa fração de segundo de deslizar ou continuar. Uma foto nítida, bem iluminada e genuína, com uma expressão calorosa, funciona sempre melhor.' },
        { t: 'h2', text: 'Como obter fotos de encontros com IA' },
        { t: 'ol', items: ['Carregue 8–15 selfies variadas com boa luz.', 'Treinamos um modelo de IA pessoal do seu rosto.', 'Escolha estilos descontraídos e naturais — casual, ao ar livre, lifestyle.', 'Descarregue um conjunto de fotos em ~30 minutos.'] },
        { t: 'h2', text: 'Dicas para boas fotos de encontros' },
        { t: 'ul', items: ['Comece com uma foto nítida de cabeça e ombros, a sorrir.', 'Misture visuais descontraídos, casual e ao ar livre para dar variedade.', 'Mantenha a autenticidade — as fotos devem parecer-se claramente consigo.', 'Evite o excesso de edição; natural e simpático vence o demasiado polido.'] },
        { t: 'h2', text: 'No seu melhor — e ainda você' },
        { t: 'p', text: 'O objetivo é a sua melhor versão, mais confiante, não outra pessoa. A Nova Imago é treinada com as suas próprias selfies, por isso os resultados parecem-se consigo num ótimo dia — perfeito para uma primeira impressão genuína.' },
      ],
      ctaText: 'Criar as minhas fotos de encontros', ctaSub: 'Prontas em ~30 minutos · garantia de reembolso',
    },
  },

  'ai-headshots-for-business-teams': {
    en: {
      metaTitle: 'AI Headshots for Business & Teams — Consistent Company Photos',
      metaDescription: 'Professional, consistent headshots for your whole team or website — without scheduling a photographer for everyone. AI headshots for business, ready in minutes.',
      h1: 'AI Headshots for Business & Teams',
      intro: 'Need professional photos of your team for your website, LinkedIn or pitch deck? Coordinating a photographer for everyone is expensive and hard to schedule — especially with remote or hybrid teams. Nova Imago gives every team member consistent, professional headshots from a few selfies, in minutes.',
      blocks: [
        { t: 'h2', text: 'Why consistent team photos matter' },
        { t: 'p', text: 'A website or “About us” page with matching, professional headshots looks credible and trustworthy. Mismatched selfies and different backgrounds make even a great company look unpolished.' },
        { t: 'h2', text: 'Perfect for remote and hybrid teams' },
        { t: 'p', text: 'No need to fly everyone to one location or book studio slots. Each team member uploads a few selfies from wherever they are and gets on-brand headshots — with the same style and background across the whole team.' },
        { t: 'h2', text: 'How it works for teams' },
        { t: 'ol', items: ['Each person uploads 8–15 selfies.', 'We train a personal AI model for each of them.', 'Everyone picks the same agreed style and background.', 'Download consistent, professional headshots in minutes.'] },
        { t: 'h2', text: 'Where to use them' },
        { t: 'ul', items: ['Team and “About us” pages', 'LinkedIn profiles and email signatures', 'Pitch decks and press kits', 'Conference badges and speaker profiles'] },
        { t: 'h2', text: 'Cost-effective at any size' },
        { t: 'p', text: 'Instead of a per-person studio fee, you get professional headshots for the whole team at a fraction of the cost — and new hires can be added anytime, matching the same look.' },
      ],
      ctaText: 'Get headshots for your team', ctaSub: 'Consistent, on-brand · ready in minutes',
    },
    nl: {
      metaTitle: 'AI-headshots voor bedrijven & teams — consistente bedrijfsfoto’s',
      metaDescription: 'Professionele, consistente headshots voor je hele team of website — zonder voor iedereen een fotograaf in te plannen. AI-headshots voor bedrijven, klaar in minuten.',
      h1: 'AI-headshots voor bedrijven & teams',
      intro: 'Professionele foto’s nodig van je team voor je website, LinkedIn of pitch deck? Voor iedereen een fotograaf regelen is duur en lastig te plannen — zeker met remote of hybride teams. Nova Imago geeft elk teamlid consistente, professionele headshots uit een paar selfies, in minuten.',
      blocks: [
        { t: 'h2', text: 'Waarom consistente teamfoto’s ertoe doen' },
        { t: 'p', text: 'Een website of “Over ons”-pagina met bijpassende, professionele headshots oogt geloofwaardig en betrouwbaar. Ongelijke selfies en verschillende achtergronden laten zelfs een sterk bedrijf onverzorgd lijken.' },
        { t: 'h2', text: 'Perfect voor remote en hybride teams' },
        { t: 'p', text: 'Niemand hoeft naar één locatie te reizen of studiotijd te boeken. Elk teamlid uploadt een paar selfies vanaf waar ze ook zijn en krijgt on-brand headshots — met dezelfde stijl en achtergrond voor het hele team.' },
        { t: 'h2', text: 'Zo werkt het voor teams' },
        { t: 'ol', items: ['Elke persoon uploadt 8–15 selfies.', 'Wij trainen voor elk een persoonlijk AI-model.', 'Iedereen kiest dezelfde afgesproken stijl en achtergrond.', 'Download consistente, professionele headshots in minuten.'] },
        { t: 'h2', text: 'Waar je ze gebruikt' },
        { t: 'ul', items: ['Team- en “Over ons”-pagina’s', 'LinkedIn-profielen en e-mailhandtekeningen', 'Pitch decks en persmappen', 'Conferentiebadges en sprekersprofielen'] },
        { t: 'h2', text: 'Kostenefficiënt op elke schaal' },
        { t: 'p', text: 'In plaats van een studiotarief per persoon krijg je professionele headshots voor het hele team voor een fractie van de kost — en nieuwe medewerkers voeg je op elk moment toe, in dezelfde look.' },
      ],
      ctaText: 'Headshots voor je team', ctaSub: 'Consistent en on-brand · klaar in minuten',
    },
    fr: {
      metaTitle: 'Portraits IA pour entreprises & équipes — des photos cohérentes',
      metaDescription: 'Des portraits professionnels et cohérents pour toute votre équipe ou votre site — sans planifier un photographe pour chacun. Portraits IA pour entreprises, prêts en minutes.',
      h1: 'Portraits IA pour entreprises & équipes',
      intro: 'Besoin de photos professionnelles de votre équipe pour votre site, LinkedIn ou pitch deck ? Coordonner un photographe pour tout le monde coûte cher et est difficile à planifier — surtout avec des équipes à distance ou hybrides. Nova Imago offre à chaque membre des portraits professionnels et cohérents à partir de quelques selfies, en minutes.',
      blocks: [
        { t: 'h2', text: 'Pourquoi des photos d’équipe cohérentes comptent' },
        { t: 'p', text: 'Un site ou une page « À propos » avec des portraits professionnels harmonisés inspire crédibilité et confiance. Des selfies dépareillés et des arrière-plans différents donnent un air négligé, même à une excellente entreprise.' },
        { t: 'h2', text: 'Parfait pour les équipes à distance et hybrides' },
        { t: 'p', text: 'Pas besoin de réunir tout le monde au même endroit ni de réserver des créneaux studio. Chaque membre envoie quelques selfies d’où il est et obtient des portraits à l’image de la marque — même style et même arrière-plan pour toute l’équipe.' },
        { t: 'h2', text: 'Comment ça marche pour les équipes' },
        { t: 'ol', items: ['Chaque personne envoie 8 à 15 selfies.', 'Nous entraînons un modèle IA personnel pour chacun.', 'Tout le monde choisit le même style et arrière-plan convenus.', 'Téléchargez des portraits professionnels cohérents en minutes.'] },
        { t: 'h2', text: 'Où les utiliser' },
        { t: 'ul', items: ['Pages équipe et « À propos »', 'Profils LinkedIn et signatures e-mail', 'Pitch decks et dossiers de presse', 'Badges de conférence et profils d’intervenants'] },
        { t: 'h2', text: 'Rentable à toute échelle' },
        { t: 'p', text: 'Au lieu d’un tarif studio par personne, vous obtenez des portraits professionnels pour toute l’équipe à une fraction du coût — et les nouvelles recrues s’ajoutent à tout moment, avec le même rendu.' },
      ],
      ctaText: 'Des portraits pour votre équipe', ctaSub: 'Cohérents et à votre image · prêts en minutes',
    },
    de: {
      metaTitle: 'KI-Headshots für Unternehmen & Teams — einheitliche Firmenfotos',
      metaDescription: 'Professionelle, einheitliche Headshots für dein ganzes Team oder deine Website — ohne für jeden einen Fotografen zu planen. KI-Headshots für Unternehmen, in Minuten fertig.',
      h1: 'KI-Headshots für Unternehmen & Teams',
      intro: 'Du brauchst professionelle Fotos deines Teams für Website, LinkedIn oder Pitch Deck? Für alle einen Fotografen zu koordinieren ist teuer und schwer zu planen — besonders bei Remote- oder Hybrid-Teams. Nova Imago liefert jedem Teammitglied einheitliche, professionelle Headshots aus ein paar Selfies, in Minuten.',
      blocks: [
        { t: 'h2', text: 'Warum einheitliche Teamfotos wichtig sind' },
        { t: 'p', text: 'Eine Website oder „Über uns“-Seite mit einheitlichen, professionellen Headshots wirkt glaubwürdig und vertrauenswürdig. Uneinheitliche Selfies und verschiedene Hintergründe lassen selbst ein starkes Unternehmen ungepflegt aussehen.' },
        { t: 'h2', text: 'Perfekt für Remote- und Hybrid-Teams' },
        { t: 'p', text: 'Niemand muss an einen Ort reisen oder Studiotermine buchen. Jedes Teammitglied lädt ein paar Selfies von überall hoch und erhält markenkonforme Headshots — mit demselben Stil und Hintergrund im ganzen Team.' },
        { t: 'h2', text: 'So funktioniert es für Teams' },
        { t: 'ol', items: ['Jede Person lädt 8–15 Selfies hoch.', 'Wir trainieren für jede:n ein persönliches KI-Modell.', 'Alle wählen denselben vereinbarten Stil und Hintergrund.', 'Lade einheitliche, professionelle Headshots in Minuten herunter.'] },
        { t: 'h2', text: 'Wo du sie einsetzt' },
        { t: 'ul', items: ['Team- und „Über uns“-Seiten', 'LinkedIn-Profile und E-Mail-Signaturen', 'Pitch Decks und Pressemappen', 'Konferenzausweise und Speaker-Profile'] },
        { t: 'h2', text: 'Kosteneffizient in jeder Größe' },
        { t: 'p', text: 'Statt einer Studiogebühr pro Person bekommst du professionelle Headshots für das ganze Team zu einem Bruchteil der Kosten — und neue Mitarbeitende lassen sich jederzeit im selben Look ergänzen.' },
      ],
      ctaText: 'Headshots für dein Team', ctaSub: 'Einheitlich & markenkonform · in Minuten fertig',
    },
    es: {
      metaTitle: 'Retratos con IA para empresas y equipos — fotos coherentes',
      metaDescription: 'Retratos profesionales y coherentes para todo tu equipo o tu web — sin agendar un fotógrafo para cada uno. Retratos con IA para empresas, listos en minutos.',
      h1: 'Retratos con IA para empresas y equipos',
      intro: '¿Necesitas fotos profesionales de tu equipo para tu web, LinkedIn o pitch deck? Coordinar un fotógrafo para todos es caro y difícil de agendar — sobre todo con equipos remotos o híbridos. Nova Imago da a cada miembro retratos profesionales y coherentes a partir de unos selfies, en minutos.',
      blocks: [
        { t: 'h2', text: 'Por qué importan las fotos de equipo coherentes' },
        { t: 'p', text: 'Una web o página “Sobre nosotros” con retratos profesionales a juego transmite credibilidad y confianza. Selfies dispares y fondos distintos hacen que hasta una gran empresa parezca poco cuidada.' },
        { t: 'h2', text: 'Perfecto para equipos remotos e híbridos' },
        { t: 'p', text: 'No hace falta reunir a todos en un sitio ni reservar horas de estudio. Cada miembro sube unos selfies desde donde esté y obtiene retratos acordes a la marca — con el mismo estilo y fondo en todo el equipo.' },
        { t: 'h2', text: 'Cómo funciona para equipos' },
        { t: 'ol', items: ['Cada persona sube 8–15 selfies.', 'Entrenamos un modelo de IA personal para cada una.', 'Todos eligen el mismo estilo y fondo acordados.', 'Descarga retratos profesionales y coherentes en minutos.'] },
        { t: 'h2', text: 'Dónde usarlos' },
        { t: 'ul', items: ['Páginas de equipo y “Sobre nosotros”', 'Perfiles de LinkedIn y firmas de correo', 'Pitch decks y kits de prensa', 'Acreditaciones de congresos y perfiles de ponentes'] },
        { t: 'h2', text: 'Rentable a cualquier escala' },
        { t: 'p', text: 'En lugar de una tarifa de estudio por persona, consigues retratos profesionales para todo el equipo por una fracción del coste — y puedes añadir a nuevas incorporaciones cuando quieras, con el mismo aspecto.' },
      ],
      ctaText: 'Retratos para tu equipo', ctaSub: 'Coherentes y de marca · listos en minutos',
    },
    it: {
      metaTitle: 'Ritratti IA per aziende e team — foto aziendali coerenti',
      metaDescription: 'Ritratti professionali e coerenti per tutto il team o per il sito — senza organizzare un fotografo per ciascuno. Ritratti IA per aziende, pronti in minuti.',
      h1: 'Ritratti IA per aziende e team',
      intro: 'Ti servono foto professionali del team per il sito, LinkedIn o il pitch deck? Coordinare un fotografo per tutti è costoso e difficile da pianificare — soprattutto con team remoti o ibridi. Nova Imago offre a ogni membro ritratti professionali e coerenti da qualche selfie, in minuti.',
      blocks: [
        { t: 'h2', text: 'Perché contano foto di team coerenti' },
        { t: 'p', text: 'Un sito o una pagina “Chi siamo” con ritratti professionali uniformi trasmette credibilità e fiducia. Selfie disomogenei e sfondi diversi fanno sembrare poco curata anche un’ottima azienda.' },
        { t: 'h2', text: 'Perfetto per team remoti e ibridi' },
        { t: 'p', text: 'Non serve riunire tutti in un luogo né prenotare slot in studio. Ogni membro carica qualche selfie da dove si trova e ottiene ritratti in linea con il brand — stesso stile e sfondo per tutto il team.' },
        { t: 'h2', text: 'Come funziona per i team' },
        { t: 'ol', items: ['Ogni persona carica 8–15 selfie.', 'Alleniamo un modello IA personale per ciascuno.', 'Tutti scelgono lo stesso stile e sfondo concordati.', 'Scarica ritratti professionali e coerenti in minuti.'] },
        { t: 'h2', text: 'Dove usarli' },
        { t: 'ul', items: ['Pagine team e “Chi siamo”', 'Profili LinkedIn e firme e-mail', 'Pitch deck e press kit', 'Badge per conferenze e profili relatori'] },
        { t: 'h2', text: 'Conveniente a ogni dimensione' },
        { t: 'p', text: 'Invece di una tariffa da studio a persona, ottieni ritratti professionali per tutto il team a una frazione del costo — e i nuovi assunti si aggiungono in qualsiasi momento, con lo stesso look.' },
      ],
      ctaText: 'Ritratti per il tuo team', ctaSub: 'Coerenti e in linea col brand · pronti in minuti',
    },
    pt: {
      metaTitle: 'Retratos com IA para empresas e equipas — fotos coerentes',
      metaDescription: 'Retratos profissionais e coerentes para toda a equipa ou o site — sem agendar um fotógrafo para cada um. Retratos com IA para empresas, prontos em minutos.',
      h1: 'Retratos com IA para empresas e equipas',
      intro: 'Precisa de fotos profissionais da equipa para o site, LinkedIn ou pitch deck? Coordenar um fotógrafo para todos é caro e difícil de agendar — sobretudo com equipas remotas ou híbridas. A Nova Imago dá a cada membro retratos profissionais e coerentes a partir de algumas selfies, em minutos.',
      blocks: [
        { t: 'h2', text: 'Porque importam fotos de equipa coerentes' },
        { t: 'p', text: 'Um site ou página “Sobre nós” com retratos profissionais uniformes transmite credibilidade e confiança. Selfies díspares e fundos diferentes fazem até uma ótima empresa parecer pouco cuidada.' },
        { t: 'h2', text: 'Perfeito para equipas remotas e híbridas' },
        { t: 'p', text: 'Não é preciso reunir todos num local nem reservar horas de estúdio. Cada membro carrega algumas selfies de onde estiver e obtém retratos alinhados com a marca — mesmo estilo e fundo em toda a equipa.' },
        { t: 'h2', text: 'Como funciona para equipas' },
        { t: 'ol', items: ['Cada pessoa carrega 8–15 selfies.', 'Treinamos um modelo de IA pessoal para cada uma.', 'Todos escolhem o mesmo estilo e fundo combinados.', 'Descarregue retratos profissionais e coerentes em minutos.'] },
        { t: 'h2', text: 'Onde usá-los' },
        { t: 'ul', items: ['Páginas de equipa e “Sobre nós”', 'Perfis de LinkedIn e assinaturas de e-mail', 'Pitch decks e kits de imprensa', 'Crachás de conferência e perfis de oradores'] },
        { t: 'h2', text: 'Rentável em qualquer dimensão' },
        { t: 'p', text: 'Em vez de uma tarifa de estúdio por pessoa, obtém retratos profissionais para toda a equipa por uma fração do custo — e novos colaboradores podem ser adicionados a qualquer momento, com o mesmo visual.' },
      ],
      ctaText: 'Retratos para a sua equipa', ctaSub: 'Coerentes e alinhados com a marca · prontos em minutos',
    },
  },
}

export const GUIDE_SLUGS = Object.keys(GUIDES)

// Volgorde waarin guides in de index/footer verschijnen.
export const GUIDE_ORDER = [
  'ai-headshots-for-linkedin',
  'ai-headshots-for-cv',
  'ai-photos-for-dating',
  'ai-headshots-for-business-teams',
  'ai-headshots-vs-photographer',
]

// Labels voor de blog-index + navigatie/footer, per taal.
export const GUIDES_INDEX: Record<Locale, { title: string; heading: string; intro: string }> = {
  en: { title: 'Blog', heading: 'The Nova Imago Blog', intro: 'Practical tips and guides on getting professional AI headshots for LinkedIn, your CV, dating, business and more.' },
  nl: { title: 'Blog', heading: 'De Nova Imago Blog', intro: 'Praktische tips en gidsen over professionele AI-headshots voor LinkedIn, je cv, dating, bedrijven en meer.' },
  fr: { title: 'Blog', heading: 'Le blog Nova Imago', intro: 'Conseils et guides pratiques pour des portraits IA professionnels : LinkedIn, CV, rencontres, entreprises et plus.' },
  de: { title: 'Blog', heading: 'Der Nova Imago Blog', intro: 'Praktische Tipps und Ratgeber für professionelle KI-Headshots: LinkedIn, Lebenslauf, Dating, Unternehmen und mehr.' },
  es: { title: 'Blog', heading: 'El blog de Nova Imago', intro: 'Consejos y guías prácticas para retratos con IA profesionales: LinkedIn, CV, citas, empresas y más.' },
  it: { title: 'Blog', heading: 'Il blog di Nova Imago', intro: 'Consigli e guide pratiche per ritratti IA professionali: LinkedIn, CV, incontri, aziende e altro.' },
  pt: { title: 'Blog', heading: 'O blog da Nova Imago', intro: 'Dicas e guias práticos para retratos com IA profissionais: LinkedIn, CV, encontros, empresas e mais.' },
}

// Blog-metadata die niet per taal verschilt: hero-afbeelding + publicatiedatum per artikel.
export const BLOG_AUTHOR = 'Nova Imago'
export const GUIDE_META: Record<string, { image: string; date: string }> = {
  'ai-headshots-for-linkedin': { image: '/images/renata-after.jpg', date: '2026-09-19' },
  'ai-headshots-for-cv': { image: '/images/stijn-after.jpg', date: '2026-09-19' },
  'ai-photos-for-dating': { image: '/images/nathalie-after.webp', date: '2026-09-19' },
  'ai-headshots-for-business-teams': { image: '/images/headshot-42.webp', date: '2026-09-19' },
  'ai-headshots-vs-photographer': { image: '/images/britt-after.webp', date: '2026-09-19' },
}

// Tags per artikel, per taal (voor de blogkaarten + artikelpagina).
export const GUIDE_TAGS: Record<string, Record<Locale, string[]>> = {
  'ai-headshots-for-linkedin': { en: ['LinkedIn', 'profile photo', 'professional'], nl: ['LinkedIn', 'profielfoto', 'professioneel'], fr: ['LinkedIn', 'photo de profil', 'professionnel'], de: ['LinkedIn', 'Profilfoto', 'professionell'], es: ['LinkedIn', 'foto de perfil', 'profesional'], it: ['LinkedIn', 'foto profilo', 'professionale'], pt: ['LinkedIn', 'foto de perfil', 'profissional'] },
  'ai-headshots-for-cv': { en: ['CV', 'resume', 'job application'], nl: ['cv', 'sollicitatie', 'carrière'], fr: ['CV', 'candidature', 'emploi'], de: ['Lebenslauf', 'Bewerbung', 'Beruf'], es: ['CV', 'candidatura', 'empleo'], it: ['CV', 'candidatura', 'lavoro'], pt: ['CV', 'candidatura', 'emprego'] },
  'ai-photos-for-dating': { en: ['dating', 'profile photo', 'online dating'], nl: ['dating', 'profielfoto', 'online daten'], fr: ['rencontres', 'photo de profil', 'dating en ligne'], de: ['Dating', 'Profilfoto', 'Online-Dating'], es: ['citas', 'foto de perfil', 'dating online'], it: ['incontri', 'foto profilo', 'dating online'], pt: ['encontros', 'foto de perfil', 'dating online'] },
  'ai-headshots-for-business-teams': { en: ['business', 'team photos', 'company'], nl: ['bedrijf', 'teamfoto’s', 'onderneming'], fr: ['entreprise', 'photos d’équipe', 'société'], de: ['Unternehmen', 'Teamfotos', 'Firma'], es: ['empresa', 'fotos de equipo', 'compañía'], it: ['azienda', 'foto del team', 'società'], pt: ['empresa', 'fotos de equipa', 'negócio'] },
  'ai-headshots-vs-photographer': { en: ['comparison', 'photographer', 'AI headshots'], nl: ['vergelijking', 'fotograaf', 'AI-headshots'], fr: ['comparaison', 'photographe', 'portraits IA'], de: ['Vergleich', 'Fotograf', 'KI-Headshots'], es: ['comparación', 'fotógrafo', 'retratos IA'], it: ['confronto', 'fotografo', 'ritratti IA'], pt: ['comparação', 'fotógrafo', 'retratos IA'] },
}
